### ISSUE TITLE
How do loadings plots work?

### ISSUE THREAD

**Issue by eric-czech** [privefl/bigstatsr#100]
Hi @privefl , I have what is hopefully an easy question for you.  I'm trying to understand how loadings plots are generated and I can't understand what's going on in [plot.big_SVD](https://github.com/privefl/bigstatsr/blob/810347dfdbc7b625f0c2907e45e111764c47da8c/R/plot.R#L78).  Specifically, is this a bug in the code?

```R
    if (length(loadings) > 1) { # Line 146

      all.p <- lapply(loadings, function(i) {
        #*** This "loading" argument doesn't exist in the signature (but "loadings" does)
        #***  and since it's a kw arg, it doesn't go into ... either (so assert_nodots won't catch it)
        p <- plot(x, type = "loadings", loading = i, coeff = coeff)
        p$layers[[1]] <- NULL
        p + geom_hex() + scale_fill_viridis_c()
      })

      plot_grid(plotlist = all.p, align = "hv", ncol = ncol, scale = 0.95)

    } else {

      p <- MY_THEME(qplot(y = x$v[, loadings]), coeff = coeff) +
        labs(title = paste0("Loadings of PC", loadings),
             x = "Column index", y = NULL)

      nval <- nrow(x$v)
      `if`(nval > 12, p, p + scale_x_discrete(limits = seq_len(nval)))

    }
```

Am I looking in the right place for how the plots in your posts like [how-to-PCA](https://privefl.github.io/bigsnpr/articles/how-to-PCA.html) were generated?  I get lost at trying to follow what that ```loading``` argument is doing above since it seems to be calling the same function (recursively) that has ```loadings``` but should, I think, ignore ```loading```.

Any advice on how qqplot with only the y aesthetic gives something meaningful in a hexbin would be greatly appreciated too -- though maybe my confusion there is related to what the recursive calls are supposed to do?

Thank you!  It's a great library and I appreciate all your posts btw.

**Comment by privefl** [comment]
I would not call it a bug, but rather a typo.
You're right that `loading` should be `loadings` instead, but because of partial matching or arguments in R, it is basically the same.
E.g. you can do
```
test <- function(aaa) aaa + 1
test(a = 2)
```

**Comment by privefl** [comment]
As for the second part, you would like a qqplot with hex bins?

I think you can use the same code. Meaning:
```
p$layers[[1]] <- NULL
p + geom_hex() + scale_fill_viridis_c()
```
It removes the first layer (of points) and put some layer of hex instead (+ with some nice color palette).

**Comment by eric-czech** [comment]
Oh right, forgot about that in R.  Where I was going with the qplot question is isn't ```x$v[, loadings]``` a vector (given that the code would ensure loadings contains a single index)?  I got that the code is reseting the layer as a hexbin but I couldn't understand why a single vector would make sense with that layer.  Maybe a better way to put that is simply what does ```x$v[,loadings]``` contain?  I would have thought it was just a single column from the right singular vectors.  If it is, I can't see how you get a meaningful hexbin plot from it.

Thanks for the quick response!

**Comment by privefl** [comment]
Yes, it is just one column from the right singular vectors. 
Just the same plot when you want to see one vector of loadings, but instead of points, you get hex bins.
The goal is to make the plot faster.

**Comment by eric-czech** [comment]
Ahh sorry, I had it in my head that the y axis was more likely to represent a distribution across the samples (weighted by loading) or something of the like.  Now I'm following, thanks again.
