### ISSUE TITLE
Subsetting matrix--Error when mapping file:   Cannot allocate memory.

### ISSUE THREAD

**Issue by mj-thompson** [privefl/bigstatsr#102]
Hi,

I'm not sure if this is an issue with bigstatsr or bigsnpr but I'm attempting to subset a genotype matrix from bigsnpr. Namely, I want to subset some individuals and some snps. In the past, I was able to do so using code that looks as follows:

`geno_mat$genotypes[individuals_idx, snps_idx]`

but this recently started to return with an error: 

`Error in getXPtrFBM(path = .self$bk, n = .self$nrow, m = .self$ncol, type = .self$type): Error when mapping file:
  Cannot allocate memory.

Traceback:

1. t(geno_mat$genotypes[individuals_idx, snps_idx])
2. geno_mat$genotypes[individuals_idx, snps_idx]
3. geno_mat$genotypes[individuals_idx, snps_idx]
4. extract_matrix(x, transform_ind(i, n), transform_ind(j, m))
5. decodeMat(extractMat(x$address, i, j), x$code256)
6. extractMat(x$address, i, j)
7. x$address
8. x$address
9. get(what, envir = selfEnv)
10. (new("activeBindingFunction", .Data = function () 
  . {
  .     if (identical(.self$extptr, NIL_PTR)) {
  .         .self$extptr <- getXPtrFBM(path = .self$bk, n = .self$nrow, 
  .             m = .self$ncol, type = .self$type)
  .     }
  .     .self$extptr
  . }))()
11. getXPtrFBM(path = .self$bk, n = .self$nrow, m = .self$ncol, type = .self$type)`

I tried then to use a few of the built in functions with bigsnpr and bigstatsr:
`test<-subset(geno_mat, ind.row=individuals_idx, ind.col=snps_idx )`

and as a simple test
`tmp<-big_apply(geno_mat$genotypes, a.FUN = function(X, ind) {
  X[,ind]
}, a.combine = "c()", ind = snps_idx, ncores = 1, block.size = 500)`

The issue persists even attempting to grab a single entry from the matrix such as:
`geno_mat$genotypes[1,1]`

I'm operating on a university cluster, and I'm wondering if maybe their memory management is now more strict. However, the number of individuals will be less than 300, and the number of snps less than 10,000, so I would assume that the operation shouldn't be too memory intensive (e.g. I attempt to run these lines using 8g virtual memory). I've also attempted to supply a backingfile to the current working directory rather than simply using the tmp directory. Do you have any suggestions of where to look?

Thank you for your help.

The session info looks as follows, along with some output of attaching the bigsnp object:

> R version 3.5.1 (2018-07-02)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: CentOS release 6.10 (Final)
> 
> Matrix products: default
> BLAS: /u/local/apps/R/3.5.1/gcc-4.9.3_MKL-2018/lib64/R/lib/libRblas.so
> LAPACK: /u/local/apps/R/3.5.1/gcc-4.9.3_MKL-2018/lib64/R/lib/libRlapack.so
> 
> locale:
>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
>  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
>  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
>  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
> [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] glmnet_2.0-18     foreach_1.4.7     Matrix_1.2-15     data.table_1.12.2
> [5] bigsnpr_1.2.2     bigstatsr_1.1.4  
> 
> loaded via a namespace (and not attached):
>  [1] Rcpp_1.0.3         pillar_1.4.3       compiler_3.5.1     bigparallelr_0.2.3
>  [5] base64enc_0.1-3    iterators_1.0.12   tools_3.5.1        digest_0.6.23     
>  [9] uuid_0.1-2         lattice_0.20-38    jsonlite_1.6       evaluate_0.12     
> [13] lifecycle_0.1.0    tibble_2.1.3       gtable_0.3.0       pkgconfig_2.0.3   
> [17] rlang_0.4.4        IRdisplay_0.7.0    flock_0.7          IRkernel_0.8.14   
> [21] parallel_3.5.1     repr_0.18          bigassertr_0.1.2   dplyr_0.8.3       
> [25] cowplot_1.0.0      grid_3.5.1         tidyselect_0.2.5   glue_1.3.1        
> [29] R6_2.4.1           pbdZMQ_0.3-3       ggplot2_3.2.1      purrr_0.2.5       
> [33] magrittr_1.5       scales_1.1.0       codetools_0.2-15   htmltools_0.3.6   
> [37] assertthat_0.2.1   colorspace_1.4-1   lazyeval_0.2.2     munsell_0.5.0     
> [41] doParallel_1.0.15  crayon_1.3.4      
> 
> FBM from an old version? Reconstructing..
> You should use `snp_save()`.

**Comment by privefl** [comment]
Thanks for reporting.

Have you tried asking for some completely new resources? (e.g. a new node)
It might be that you've exhausted all memory and there is nothing more you can do.

I am not 100% sure how virtual memory works and how you would be able to free some to get more.
Unfortunately, I don't remember having this issue. Or maybe when I exhaust `/tmp/` space.
What is the output of `df -h /tmp/`?

**Comment by mj-thompson** [comment]
Thanks for the quick reply. I tried two additional nodes as well, I will try updating the requested memory by a few g.

Interestingly...
> df -h /tmp/
> Filesystem      Size  Used Avail Use% Mounted on
> /dev/sda3       894G  1.4G  848G   1% /work

> print(object.size(x=lapply(ls(), get)), units="Mb")
> 1423 Mb
> 
> gc()
>           used  (Mb) gc trigger   (Mb)  max used   (Mb)
> Ncells  9164684 489.5   14970594  799.6   9497314  507.3
> Vcells 81246975 619.9  165787965 1264.9 165779539 1264.8

I will try a few more things then contact the cluster manager. I'll report back if I find anything out/a solution.

**Comment by mj-thompson** [comment]
It was a careless mistake of asking for too little resources (upping the vmem to 12g solved the issue). I appreciate the help!

**Comment by mj-thompson** [comment]
Hi Florian.

The error seems to return. I've tried increasing the memory significantly, but eventually it fails For example, I'm fitting a linear model for some phenotype explained by SNPs, and doing this for 100 phenotypes in a for-loop. After a dozen or so phenotypes, the job will fail. Is it guaranteed that using the `[` accessor will only load into memory the chosen indices, i.e. A[row.index, col.index] will only load a matrix of size |row.index|x|col.index| into memory? When I can, I'm using the big linear model functions to operate on the bigsnpr object, but there are a few cases e.g. constructing a sparse/block matrix where I want to generate my own and use glmnet.

**Comment by privefl** [comment]
The error you report ends with `getXPtrFBM(path = .self$bk, n = .self$nrow, m = .self$ncol, type = .self$type)`, which means that there is an error when memory-mapping the file, i.e. before accessing the data in R.

Maybe try to asssign the FBM object in some variable, and use it in your loop. I fear that it might try to memory-map again because of using temporary objects. E.g. use
```
G <- geno_mat$genotypes
G[individuals_idx, snps_idx]
```

**Comment by privefl** [comment]
Also, I would recommend to always look at the resources you're using, e.g. with `top`.
You can quickly spot problems if you do that.

**Comment by mj-thompson** [comment]
Thank you for the tips, I'll try both. In the meantime, I've asked those who run the cluster about changes to memory, vmemory and temp directories. I'll keep you updated, and it seems like this is not an issue with the package, feel free to close it and I can email youif you like.
