### ISSUE TITLE
numeric precission issues in summary alpha values

### ISSUE THREAD

**Issue by RichardJActon** [privefl/bigstatsr#106]
The values in the alpha column of the output of the summary function are not exactly those input - e.g. an alpha of 0.001 has an exact value of 0.001000000000000000020817. Revealed by:

`model %>% summary() %>% pull(alpha) %>% print(digits = 22)`

I'm guessing this might arise from a type conversion issue maybe a 32bit float in the c++ being converted to a double in R or something like that?

I discovered this when trying to look at the results for specific alpha values when something like the below was yielding `NA` values as there was no exact match in the tibble.

`model %>% summary() %>% filter(alpha = 0.001)`

**Comment by privefl** [comment]
What input `alpha` do you use?

**Comment by privefl** [comment]
By the way, this works for me:
```
library(bigstatsr)
set.seed(1)

# simulating some data
N <- 230
M <- 730
X <- FBM(N, M, init = rnorm(N * M, sd = 5))
y <- rowSums(X[, 1:10]) + rnorm(N)
covar <- matrix(rnorm(N * 3), N)

ind.train <- sort(sample(nrow(X), 150))
ind.test <- setdiff(rows_along(X), ind.train)

# fitting model for multiple lambdas and alphas
model <- big_spLinReg(X, y[ind.train], ind.train = ind.train,
                      covar.train = covar[ind.train, ],
                      alphas = 1e-3, warn = FALSE)

# peek at the models
library(dplyr)
model %>% summary() %>% filter(alpha == 0.001)
```

**Comment by RichardJActon** [comment]
I'll try and get back to you with a minimal reproducible example when I find the time - It seems to be occurring inconsistently.

**Comment by privefl** [comment]
Any update on this?

**Comment by RichardJActon** [comment]
I have not been able to reproduce the issue outside of very contrived situations like this:

    library(bigstatsr)
    set.seed(1)
    
    a <- 0.2
    
    # simulating some data
    N <- 230
    M <- 730
    X <- FBM(N, M, init = rnorm(N * M, sd = 5))
    y <- rowSums(X[, 1:10]) + rnorm(N)
    covar <- matrix(rnorm(N * 3), N)
    
    ind.train <- sort(sample(nrow(X), 150))
    ind.test <- setdiff(rows_along(X), ind.train)
    
    # fitting model for multiple lambdas and alphas
    model <- big_spLinReg(X, y[ind.train], ind.train = ind.train,
                          covar.train = covar[ind.train, ],
                          alphas = a, warn = FALSE)
    
    # peek at the models
    library(dplyr)
    print(a, digits = 22)
    model %>% summary() %>% filter(alpha == 0.2000000000000000999)
    model %>% summary() %>% pull(alpha) %>% print(digits = 22)
    

Which does not represent a real-world issue, can't figure out how I might have run afoul of rounding errors that small with alphas specified with no more precision than 0.001. 

Shall I close the issue as I can't repoduce it?

(single `=` was just a typo in the initial issue)

**Comment by privefl** [comment]
If I use `model %>% summary() %>% filter(alpha == 0.2)`, then it works, right?

**Comment by RichardJActon** [comment]
yes

**Comment by privefl** [comment]
I'm not sure what the issue is then?
