### ISSUE TITLE
Informations on scaling 

### ISSUE THREAD

**Issue by glageosa** [privefl/bigstatsr#107]
As you explained to me, you don't directly scale the data but uses linear algebra technics to scale your data, are these technics directly implemented in your functions ? For example, if I need to use standardize genotypes to do the GWAS, does the GWAS performs a scaling on the genotypes or do I have to do it myself ?
Thanks !

**Comment by privefl** [comment]
Usually a parameter `fun.scaling` (or `center` and `scale`) is used for scaling.

In GWAS, you don't need to scale anything. What do you mean?

**Comment by glageosa** [comment]
Well if I want to do the logistic regression and then compute the PRS and AUC, the genotypes aren't supposed to be standardized ?

**Comment by glageosa** [comment]
I'm building a Liability Threshold Model, if I want to assign a phenotype to the genotypes I had to first standardize the genotypes and then with the given threshold I need to determine the phenotypes of all individuals

**Comment by privefl** [comment]
Do you mean simulating phenotypes using a LTM?

**Comment by glageosa** [comment]
Yes ! Sorry I'm new to this so maybe I explain poorly my intentions :p I think I figured out what you meant and how to do the study, thanks !
