### ISSUE TITLE
About big_cor - what correlation is used?

### ISSUE THREAD

**Issue by RdeBiotec** [privefl/bigstatsr#114]
Hi!

First of all, congrats for the package, it's really cool!

I am now trying to use big_cor for some analysis. I have some suggestions.

Would it be possible to include in the manual/function info that the correlation that it uses is the Pearson correlation (it's not specified there)?

Also, would it be possible to expand it to include an option to calculate Kendall or Spearman correlation? For some types of data they are more appropriate than Pearson.

Thanks and best regards!

**Comment by privefl** [comment]
Sure, I'll add that it is Pearson correlation.

However, computing Kendall or Spearman is much for computationally intensive and might be infeasible for large matrices.

**Comment by privefl** [comment]
You can always compute them by blocks using `big_apply()`.

**Comment by RdeBiotec** [comment]
True! I will take a look. Thanks a lot!
