### ISSUE TITLE
Unable to load bigsnpr

### ISSUE THREAD

**Issue by Mahantesh-Biradar** [privefl/bigstatsr#115]
> library(bigsnpr)
Loading required package: bigstatsr
Error: package or namespace load failed for ‘bigstatsr’:
 package ‘rlang’ does not have a namespace
Error: package ‘bigstatsr’ could not be loaded
In addition: Warning messages:
1: package ‘bigsnpr’ was built under R version 4.0.2 
2: package ‘bigstatsr’ was built under R version 4.0.2 

Thank You

**Comment by privefl** [comment]
Try to reinstall {rlang} after resarting R.

**Comment by Mahantesh-Biradar** [comment]
Hi Florian

I tried it and

> library(bigsnpr)
Loading required package: bigstatsr
Error: package or namespace load failed for ‘bigstatsr’ in inDL(x,
as.logical(local), as.logical(now), ...):
 unable to load shared object
'C:/Users/Mahantesh/Documents/R/win-library/4.0/Rcpp/libs/x64/Rcpp.dll':
  LoadLibrary failure:  The specified procedure could not be found.

Error: package ‘bigstatsr’ could not be loaded
In addition: Warning messages:
1: package ‘bigsnpr’ was built under R version 4.0.2
2: package ‘bigstatsr’ was built under R version 4.0.2

Thanks in Advance

**Comment by privefl** [comment]
Try to reinstall {Rcpp}.

**Comment by Mahantesh-Biradar** [comment]
I installed Rcpp and tried again

> library(bigsnpr)
Loading required package: bigstatsr
Error: package or namespace load failed for ‘bigstatsr’ in inDL(x,
as.logical(local), as.logical(now), ...):
 unable to load shared object
'C:/Users/Mahantesh/Documents/R/win-library/4.0/Rcpp/libs/x64/Rcpp.dll':
  LoadLibrary failure:  The specified procedure could not be found.

Error: package ‘bigstatsr’ could not be loaded
In addition: Warning messages:
1: package ‘bigsnpr’ was built under R version 4.0.2
2: package ‘bigstatsr’ was built under R version 4.0.2

**Comment by privefl** [comment]
Then please reinstall {bigstatsr} and try to `library(bigstatsr)`.
I don't think it has a lot to do with my packages. If you google this issue `LoadLibrary failure:  The specified procedure could not be found.`, you might find answers.
I don't have time to look deeply into this right now.

**Comment by Mahantesh-Biradar** [comment]
Thank you - let me try that way!

**Comment by privefl** [comment]
Thanks
