### ISSUE TITLE
Error in .class1(object) : object 'corr0' not found

### ISSUE THREAD

**Issue by Mahantesh-Biradar** [privefl/bigstatsr#116]
I'm trying to follow the tutorial on another computer and I'm at this stage

corr <- bigsparser::as_SFBM(as(corr0, "dgCMatrix"))

And I get this error

> corr <- bigsparser::as_SFBM(as(corr0, "dgCMatrix"))
Error in .class1(object) : object 'corr0' not found

Thanks in advance

**Comment by privefl** [comment]
Have you run the line that creates `corr0`? Have you an error before?

**Comment by Mahantesh-Biradar** [comment]
Apologies! I have figured this out. Thanks
