### ISSUE TITLE
big_spLinReg() extracting best lambda etc.

### ISSUE THREAD

**Issue by gustavahlberg** [privefl/bigstatsr#117]
Isn't there away to get the actual lambda, beta etc for the best fitted model when using big_spLinReg()?? As far as I can understand,  I am quite limited to using  basically the function predict() to get the cv.model's the best fitted model. But I might want the actual beta and lambda estimates for other purposes. I would also like to refit the model with one lambda? Isn't there an option to specify a specific lambda value?

Thanks,
Gustav

**Comment by privefl** [comment]
Taking the function example:
```r
library(bigstatsr)

# simulating some data
set.seed(1)
N <- 230
M <- 730
X <- FBM(N, M, init = rnorm(N * M, sd = 5))
y <- rowSums(X[, 1:10]) + rnorm(N)
covar <- matrix(rnorm(N * 3), N)

ind.train <- sort(sample(nrow(X), 150))
ind.test <- setdiff(rows_along(X), ind.train)

# fitting model for multiple lambdas and alphas
test <- big_spLinReg(X, y[ind.train], ind.train = ind.train,
                     covar.train = covar[ind.train, ],
                     alphas = c(1, 0.5, 0.1, 0.01), warn = FALSE)
```

I remind you it fits many models (`length(alphas)` x `K`). Looking at only one of them, you can get:

```r
sub_mod <- test[[1]][[1]]
sub_mod$beta
sub_mod$lambda[which.min(sub_mod$loss.val)]
```

**Comment by gustavahlberg** [comment]
Thanks. But yes, that I get. But that's just the minimum lambda for one cv. I would The lambdas and betas will be diffrent in each fold.  
It would make sense to me to average the best lambda but then I would like to refit the model with that lambda. Which I can't with big_spLinReg? 
Basically I am looking for a away to reach something like COPY_cdfit_gaussian_hsr() or COPY_biglasso_part() but I can't find the function in your R code so I can't source it. 
It looks to me that the betas are averaged from best fit in each fold (keeping alphas separate of course ). I rather refit the model with the best estimated lambda I think.

**Comment by privefl** [comment]
It was not designed that way, sorry.
