### ISSUE TITLE
Fast approximation of biglasso?

### ISSUE THREAD

**Issue by privefl** [privefl/bigstatsr#12]
Find if there is a fast near-optimal rule approximation for computing multivariate linear/logistic regression on biobank-scale datasets in a few hours (or minutes).

**Comment by kaneplusplus** [comment]
You probably want to start with the [STRONG rules](http://statweb.stanford.edu/~tibs/ftp/strong.pdf) which eliminates regressors that don't project well onto the response based on the penalty. You can then apply the lasso on the remaining regressors.

If you still have too much data you can trade off estimator accuracy for computational complexity either by reducing the numerical accuracy of the slope coefficients in the standard implementation or by using [ADMM](https://dl.acm.org/citation.cfm?id=2185816). I personally prefer the former is probably faster when the data randomly distributed over concurrent partitions.

**Comment by privefl** [comment]
Thanks for the tips.
I was thinking maybe using the strong rules without checking KKT conditions.

For now, I have not the time to test this, but hopefully I will someday. 
Or maybe someone else before me :-)

**Comment by kaneplusplus** [comment]
I need to implement this for a book I'm writing. If you can wait a few weeks then I can provide a reference implementation.

**Comment by privefl** [comment]
Strong rules are implemented in the **biglasso** package of @YaohuiZeng. I'm also using the code in this package. 

I'm looking forward to see your implementation.

**Comment by kaneplusplus** [comment]
The crux STRONG is checking the KKT conditions. Below is reference code similar to what I have in the book chapter to do this.

Note that if you were going to optimize for performance, you'd probably want the vector of slope cefficients `b` to be sparse, and you could easily parallelize the call to `apply` for the case where you have a lot of active slope coefficients.

Also, note that you'd probably want to change `b == 0` to check to see when `b` is close to zero. I believe the this tolerance is 1e-6 in the `glmnet` Mortran code.

```{r}
kkt_violation <- function(X, y, b, lambda, alpha) {
  # Calculate the residuals.
  resids <- y - X %*% b

  # Calculate the projection of each variable onto the residuals.
  s <- apply(X, 2, function(xj) crossprod(xj, resids)) /
    lambda / alpha / nrow(X)

  # Return a vector indicating where the KKT conditions have been violated
  # by the variables that are currently zero.
  ret <- rep(FALSE, length(b))
  ret[(b == 0 & abs(s) >= 1)] <- TRUE
  ret
}
```
```

**Comment by privefl** [comment]
Now much faster with #14
