### ISSUE TITLE
Cannot import big tab-delimited file

### ISSUE THREAD

**Issue by ludgergoeminne** [privefl/bigstatsr#125]
Dear Florian

Thanks for developing the `bigstatsr` package, it looks really nice!

However, I have an issue while trying to convert a very big tab-delimited file (488377 rows, 14404 columns) to an FBM object, as it is too big to fully import into memory.
I followed your tutorial at: https://privefl.github.io/bigstatsr/articles/read-FBM-from-file.html
and I am using the following code to immediately convert "bigfile.tab" to an FBM object:

`bm <- bigstatsr::big_read(file = "/filepath1/bigfile.tab", select = 1:14404, nThread = 15, sep = "\t", quote = "", backingfile = "/filepath2/bigfile")`

However, after a short while, I bump into the following error:

`Error in replaceDF(x$address_rw, i, j, value) :   R type 'character' is not supported.`

I first had the CRAN version, but the problem persists when installing the latest GitHub version via:
`remotes::install_github("privefl/bigstatsr", force = TRUE)`

The `bigstatsr:::replaceDF` function does a call to `bigstatsr:::_bigstatsr_replaceDF`, which calls the file `bigstatsr.so`.

Could you perhaps tell me what might be going on and how I could fix this issue?

Unfortunately, I cannot share the tab-delimited file itself, as it is sensitive data.

Best regards

Ludger

**Comment by privefl** [comment]
Hi Ludger, thanks for using the package.

I think you're trying to read character/string data.
However, the FBM format can store only numeric data.
I would suggest you identify which columns are non-numeric and read them separately.

**Comment by privefl** [comment]
Any update on this?

**Comment by ludgergoeminne** [comment]
Hi Florian

My data also had non-numeric elements, so I had to find another solution.
In the end, I went for the disk.frame R package.
Thanks for your quick response!

Best regards

Ludger
