### ISSUE TITLE
Multiply 2 large matrices in R

### ISSUE THREAD

**Issue by baldwaprateek** [privefl/bigstatsr#126]
Hi,

I came across bigstatsr package in R and I believe this package should resolve my problem. The problem statement is as below:

I have 2 matrices with dimensions as given:

Matrix A -> 1.1 million rows * 16 columns
Matrix B -> 65000 rows * 16 columns

I want to multiply these 2 matrices and get a resultant matrix i.e. Matrix A %*% transpose(Matrix B)

As the matrices are very large, I am looking for a time effective solution which is quick and also does not hang my system.

**Comment by privefl** [comment]
I see, the problem is that you get a 1.1M x 65K matrix at the end.
You could create an FBM and compute and fill blocks of columns at a time using `big_apply()`.
Each block would look like `res[, ind] <- tcrossprod(A, B[ind, ]); NULL`.

**Comment by baldwaprateek** [comment]
U <- as.matrix(data.frame('X1'=c(1,4,3),'X2'=c(2,1,2),'X3'=c(3,1,1)))
V <- as.matrix(data.frame('X1'=c(0.5,0.1),'X2'=c(0.7,0.2),'X3'=c(0.3,0.2)))

X <- FBM(3, 2, backingfile = "test1")$save()
# If you open a new session you can do
X <- big_attach("test1.rds")
NCORES <- nb_cores()
# X = U V^T + E
big_apply(X, a.FUN = function(X, ind, U, V) {
  X[, ind] <- tcrossprod(U, V[ind, ]) + rnorm(nrow(X) * length(ind))
  NULL  ## you don't want to return anything here
}, a.combine = 'c', ncores = NCORES, U = U, V = V)


I am trying this howvere, it throws error : Error in { : 
  task 1 failed - "task 1 failed - "non-conformable arguments""

Can you help me resolve this ?

**Comment by privefl** [comment]
You're using a block size of 1, which means that you need to make sure that the subset of V stays in matrix format.
You can use `V[ind, , drop = FALSE]` instead; this should solve this issue.

**Comment by baldwaprateek** [comment]
Thank you. This  resolves this error but now when I run this on my actual dataset, I get the below error:

_Inconsistency between size of backingfile and dimension_

I am using the below line of code
X <- FBM(1112538,65536, backingfile = "test")$save()

**Comment by privefl** [comment]
What is `file.size("test.bk")`?

**Comment by baldwaprateek** [comment]
This returns me 0.

**Comment by privefl** [comment]
And if you do
```r
bigstatsr:::createFile("test2.bk", 10, 10, 8)
file.size("test2.bk")
```
?

**Comment by privefl** [comment]
Error `Inconsistency between size of backingfile and dimension` happens when you do not have enough disk space to store the FBM.
