### ISSUE TITLE
Ignore missing data in big_colstats()

### ISSUE THREAD

**Issue by opain** [privefl/bigstatsr#127]
Hello,

I am currently using the big_colstats() function to estimate the variance of genotypes. However, the results contain missing values due to some missing data within the genotype matrix. Rather than removing SNPs with missing data, I would like to estimate the variance for these SNPs using the data that is present. When using the stats var() function, this behavior can be achieved using the na.rm=T option.

Is it possible to ignore missing data for each variant when using the big_colstats() function?

Many thanks,

Ollie

**Comment by privefl** [comment]
No it is not possible, sorry. Most functions expect there are no missing value in the data.

One solution would be to impute. 
Another solution would be to use `big_apply()` to be able to (semi-efficiently) apply standard R functions on block of your matrix. E.g. something like
```r
big_apply(X, function(X, ind) {
  matrixStats::colVars(X[, ind], na.rm = TRUE)
}, ncores = nb_cores())
```

**Comment by opain** [comment]
OK. Thank you for your help. I had not seen the big_apply() function. This is very useful.
