### ISSUE TITLE
Questions about using u-values from svd object

### ISSUE THREAD

**Issue by alexey-larionov** [privefl/bigstatsr#128]
Dear Florian Prive,

I use your bigsnpr package to calculate eigenvectors to correct for population stratification.  
Briefly, I use it as the following:

1) After the required pre-processing I obtain an svd obgect using bed_autoSVD function. 
2) Then I use svd$u as my eigenvectors. 

I noted that numerically svd$u values differ from the values shown in “scores” plot.  
For avoidance of any doubts in using svd$u values, I wonder whether you could clarify 3 points for me:

1) Why is the difference between svd$u values and values shown in “scores” plot? 
2) May I use u-values directly or should I scale it as you do in the "scores" plot?
3) How can I add lines (e.g. +/- 6xSD boundaries) to the "scores" plot? 

Thank you,
Alexey

**Comment by privefl** [comment]
1. PC scores are UD in UDV^T, i.e. `sweep(svd$u, 2, svd$d, "*")`.
2. Therefore U is just proportional to PC scores (if taking each component separately)
3. The method `plot()` returns a ggplot2 object that you can modify using e.g. `+ geom_hline()`. 

PS: Note that this is usually a bad idea to use the 6-SDs criterion for PCA (cf. https://doi.org/10.1093/bioinformatics/btaa520).
