### ISSUE TITLE
Error in summary(big_sp_list) after update

### ISSUE THREAD

**Issue by philostat** [privefl/bigstatsr#130]
Hi @privefl,

I have some models created by `big_spLogReg` using `bigsnpr_1.3.0`. After updating to `bigsnpr_1.6.1`, I got the following errors when tried to use the `summary` function. 

```
> summary(mod)
Error: Input must be a vector, not NULL.
Run `rlang::last_error()` to see where the error occurred.
> rlang::last_error()
<error/vctrs_error_scalar_type>
Input must be a vector, not NULL.
Backtrace:
  1. (function (x, ...) ...
 19. vctrs:::stop_scalar_type(.Primitive("quote")(NULL), "")
 20. vctrs:::stop_vctrs(msg, "vctrs_error_scalar_type", actual = x)
Run `rlang::last_trace()` to see the full context.
```
Is there any way to access the models created by the older version? 

Many thanks.

**Comment by privefl** [comment]
Hi, this is using only {bigstatsr}, never {bigsnpr}.
Try to update {rlang} maybe?

**Comment by privefl** [comment]
Or maybe try to load {bigstatsr} before running {summary}.

**Comment by philostat** [comment]
I have updated {rlang} and also tried to load {bigstatsr} before `summary()` but still no luck. 
I have also tested it on my macbook and it gave the same error as my windows desktop after I updated {bigsnpr}.
It would be greatly appreciated if I can still access these models since I have been using this incredible package for quite some time and a lot of the models I saved were built from the older version.

**Comment by privefl** [comment]
Can you send one to me?

**Comment by philostat** [comment]
Yes, thanks for looking into that.

https://drive.google.com/file/d/12OCtHMv8LM4LB8TznjY2zdFmyyd7XnbO/view?usp=sharing

**Comment by privefl** [comment]
Thanks for reporting and sharing this file, this was very useful.

This should be fixed in the latest GitHub version, which you can install using `remotes::install_github("privefl/bigstatsr")`.

**Comment by philostat** [comment]
Thank you very much indeed for the fix!
