### ISSUE TITLE
Multiplying two FBMs

### ISSUE THREAD

**Issue by katcast** [privefl/bigstatsr#133]
Hi, I'm trying to multiply two filebacked big matrices (FBMs), but I'm having trouble as it looks like big_cprodMat is for the cross-product of a FBM and a regular matrix. I have an FBM X that is 476209  x 1387 and an FBM Xw that is also 476209  x 1387. I tried 
 sigma <- big_cprodMat(big_transpose(Xw), X)
but get the error 
Error: Incompatibility between dimensions
then I tried 
sigma <- big_cprodMat(Xw, X[])
but get the following error about size allocation since X is big so treating it like a matrix instead of an FBM is problematic:
Error: cannot allocate vector of size 4.9 Gb
I even tried: 
    sigma <- big_cprodMat(Xw, X)
but that returns the error: 
Error in { : 
  task 1 failed - "Not compatible with requested type: [type=S4; target=double]."

I see there is the function big_tcrossprodSelf but that would give me X'X instead of (Xw)'X. 

Thanks for any insights into efficiently getting a cross product of two FBMs.

**Comment by privefl** [comment]
You need to implement this with `big_apply()`.

**Comment by katcast** [comment]
Thanks! Can you provide an example of using big_apply() in this context? I don't see any examples of using this function with two FBMs. Sorry if I'm missing something obvious. Thanks again.

**Comment by privefl** [comment]
You can do something like:
```
M <- 47621 
N <- 1387
library(bigstatsr)
X  <- FBM(M, N, init = 1)
Xw <- FBM(M, N, init = 2)
cprod <- big_apply(X, function(X, ind) {
  print(ind[1])
  big_cprodMat(Xw, X[, ind])
}, a.combine  = "cbind", block.size = 200)
```

**Comment by privefl** [comment]
You can also preallocate the result matrix before and fill it if you want to save some memory.
(note that you need to use `<<-` if you use a standard R matrix.
```r
res <- matrix(NA_real_, ncol(Xw), ncol(X))
big_apply(X, function(X, ind) {
  print(ind[1])
  res[, ind] <<- big_cprodMat(Xw, X[, ind])
  NULL
}, block.size = 200)
```

**Comment by katcast** [comment]
Thanks very much!

**Comment by privefl** [comment]
This example would make a nice tutorial for this function, when I find time..

**Comment by privefl** [comment]
I have now made a vignette on how to use `big_apply()` using your case as one example.
https://privefl.github.io/bigstatsr/articles/big-apply.html

**Comment by katcast** [comment]
Awesome! Thanks so much! This is all very helpful.
