### ISSUE TITLE
(cran) Solaris specific error with `as_FBM`

### ISSUE THREAD

**Issue by talegari** [privefl/bigstatsr#134]
Hi Florian,

`as_FBM` seems to fail on solaris with the following error: Error: Not implemented on this platform: `ps_disk_usage`
This affects all downstream packages (like `bigdist`) which depends on `bigstatsr` as CRAN checks do not pass.

![image](https://user-images.githubusercontent.com/10041819/113547825-305b5d00-960c-11eb-8d42-f4bc5c961fbd.png)

I do not see any problem with linux/mac/win.

**Comment by privefl** [comment]
Yeah, I've received the same message.

I'll send an update today or tomorrow.

**Comment by privefl** [comment]
It is fixed now.
