### ISSUE TITLE
big_univLinReg does not support missing X values?

### ISSUE THREAD

**Issue by nettam** [privefl/bigstatsr#136]
I have an FBM generated from a bed with missing values (not all snps passed QC for all samples).
I would like to run a GWAS, figured using big_univLinReg would do the work, but get an error message that X contains missing values. Not sure why this would be a problem (could be ignored per snp, other packages support this.)
Other than running imputation prior to GWAS, is there any way to run this analysis using bigstatsr?

Thanks

**Comment by privefl** [comment]
Yes, most functions in both packages don't handle missing values.
This is not as straightforward to handle missing values for other functions, and it generally prevents from doing some linear algebra tricks. So, I have decided not to go down that road.

You should read from imputed data, or impute (see e.g. https://privefl.github.io/bigsnpr-extdoc/preprocessing.html#imputation).
