### ISSUE TITLE
Downloading bigstatsr not working on mac

### ISSUE THREAD

**Issue by burtoand** [privefl/bigstatsr#146]
I have tried multiple ways to download bigstatsr to my R packages:
(1) install.library
(2) remotes::install_github("privefl/bigstatsr")
(3) from Tools menu, installing from CRAN
(4) from Tools menu, installing directly bigstatsr_1.5.6.tgz from package archive 

All have resulted in some error similar to the one below:
Error: package or namespace load failed for ‘bigstatsr’ in get(method, envir = envir):
 lazy-load database '/Library/Frameworks/R.framework/Versions/4.1/Resources/library/bigstatsr/R/bigstatsr.rdb' is corrupt
In addition: Warning message:
In get(method, envir = envir) : internal error -3 in R_decompress1

**Comment by privefl** [comment]
Restart all R sessions, and try again.
