### ISSUE TITLE
Question about predictor to instance ratio when using big_spLinReg or big_spLogReg

### ISSUE THREAD

**Issue by mfknie** [privefl/bigstatsr#147]
I am currently trying to run sparse regression on a set of 9k individuals, and each individual can have up to ~600k variants after some QC/pre-filtering; I ran the analysis by chromosome, where our largest chromosome (2) has approximately 55k variants, and the smallest one (22) had about 9k variants. I generated 10 different training/test (60/40) splits on my data, and in some of the runs, I noticed that the number of non-zero effects produced by big_spLogReg was actually higher on some of the smaller chromosomes (21-22), often around ~2000, than larger ones (1-5), which never went above 1200. Additionally, the number of snps selected was not consistent across runs (e.x. one run had chr 1 - 1053 snps, chr 2 - 892, chr 21 - 925, chr 22 - 2574, while another had chr 1 - 712, chr2 - 1032, chr 21 - 281, chr 22 - 589).
I experienced a similar issue when running using both glmnet and snpnet. I thought that this might have something to do with the p >> n gap in my data; looking back at [this paper](https://www.sciencedirect.com/science/article/pii/S0002929721004201), it seems that the UK Biobank data you used had a much smaller ratio of data points to predictors,  i.e. 400k/1000k, relative to that our largest gap of 9k/55k on chromosome 2.  Is this kind of unstable behavior expected given our p to n ratio (some numerical issue with the strong selection rules checked by many of the glmnet derived software)?

**Comment by privefl** [comment]
Problem of stability selection is known for LASSO (especially with not a very large N=60% of 9K).
I guess you could get more stability by using elastic-net (i.e. 0 < `alpha` < 1).
And you should run genome-wide, not per chromosome.

**Comment by privefl** [comment]
Any update on this?

**Comment by mfknie** [comment]
Sorry for the radio silence. We are currently exploring alternative approaches to lasso, given the extensive difficulties with our data, so I will close this for now.
