### ISSUE TITLE
Bug in big_tcrossprodSelf: backingfile option missing 

### ISSUE THREAD

**Issue by mkelcb** [privefl/bigstatsr#149]
In the big_tcrossprodSelf, the backingfile option is missing. This then results in the following error:
"Error: Not enough disk space to create '/tmp/Rtmp8o1xcA/file209cd5efd38c5.bk'.".

This is because in https://github.com/privefl/bigstatsr/blob/master/R/tcrossprodSelf.R, at  this line:
`K <- FBM(n, n, init = 0)`
you try to create the backingfile at the default location , which then points to some place where I do not have permissions/enough space and there is no way to change this.

This function needs to let the user supply their own temporary directory location like for most other similar functions, so that this won't happen.

**Comment by privefl** [comment]
Yes, that's mentioned at https://github.com/privefl/bigstatsr/issues/73.

This is not really hard to implement, so I was waiting for someone else to do it.

**Comment by privefl** [comment]
In the latest GitHub version, I have just added a global option `FBM.dir`, which can be used to change the default directory used to create FBMs, which you could use as a workaround for now.

**Comment by privefl** [comment]
Does this workaround work you?

**Comment by mkelcb** [comment]
Yes thanks, you may close this topic!

**Comment by privefl** [comment]
You may too :')
