### ISSUE TITLE
Read data using ‘bigsnpr’ package and run Linear mixed effect model using other packages

### ISSUE THREAD

**Issue by biostat1400** [privefl/bigstatsr#155]
Hi,
I want to run a linear mixed effect model. I read my plink format dataset using "bigsnpr" package and now I need a matrix contain all SNPs in columns and individual IDs per row to run model. How can I give this matrix to my linear mixed effect model?

Thank you in advance for your time and consideration.

**Comment by privefl** [comment]
For a FBM (the format used to store the genotype matrix `G`), you can convert it to a standard R matrix with `G[]`.
Beware of the memory then.

**Comment by Nadi-Biostat** [comment]
Hi to all, 
I read the data using the bigsnpr package using these codes.

extdata="E:\\Running\\data"
(bedfile <- system.file("extdata", "mydata.bed", package = "bigsnpr"))
rds <- snp_readBed(bedfile, backingfile = tempfile())

After running the last line I get the following error:
Error: Path ' ' must have 'bed' extension.
My directory (extdata) contains the plink files. How to solve this error?

Thank you in advance!

**Comment by privefl** [comment]
Do not use system.file(), it is used to access a path installed in a package.
Just provide the path directly between quotes.
