### ISSUE TITLE
Any matrix multiplication function support sparse matrix?

### ISSUE THREAD

**Issue by JianqiaoWang** [privefl/bigstatsr#158]
Trying to matrix multiplication between X_{n \times p} and A_{p \times p}.  p is approximately 500,000.  A is a sparse matrices. Tried  big_prodMat function but returned error "Not compatible with requested type: [type=S4; target=double]."

**Comment by privefl** [comment]
I think you could use `big_apply()` for that.
Have a look at https://privefl.github.io/bigstatsr/articles/big-apply.html#example-2-multiplication-of-two-fbms; it should be the same principle.

If you need more help, please provide some code that you've already tried.

**Comment by JianqiaoWang** [comment]
Thanks! I will try it. It looks like a promising solution.

**Comment by privefl** [comment]
Maybe you can post your code here when you find a solution that works well for you.
