### ISSUE TITLE
Problem to install: OS X "-lgfortran" and "-lquadmath" errors

### ISSUE THREAD

**Issue by fabiennejh** [privefl/bigstatsr#16]
I have problem with the installation of the package. Here is the error message , do you have an idea of what failed ?

Thank you
Fabienne

githubinstall("bigstatsr")

ld: warning: directory not found for option '-L/usr/local/lib/gcc/x86_64-apple-darwin13.0.0/4.8.2'
ld: library not found for -lquadmath
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [bigstatsr.so] Error 1
ERROR: compilation failed for package ‘bigstatsr’
* removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/bigstatsr’
Installation failed: Command failed (1)

**Comment by privefl** [comment]
Hello,

This is a known installation problem of package {RcppArmadillo} on Mac.
Please see [this blog post](http://thecoatlessprofessor.com/programming/rcpp-rcpparmadillo-and-os-x-mavericks-lgfortran-and-lquadmath-error/).

**Comment by fabiennejh** [comment]
thank you ! 
It works now !

**Comment by privefl** [comment]
For Ubuntu users, also see https://askubuntu.com/a/736684.

**Comment by privefl** [comment]
Look also at https://github.com/fxcoudert/gfortran-for-macOS/releases (e.g. for Mac Mojave).
