### ISSUE TITLE
adding columns to FBM

### ISSUE THREAD

**Issue by chrisraynerr** [privefl/bigstatsr#160]
Hello, how can I add columns of a matrix to a FBM? I have tried a bunch of ways with no success! Many thanks!!

![Screenshot 2023-02-08 at 13 33 41](https://user-images.githubusercontent.com/17083603/217544547-58ae9bc8-111b-4307-bd7c-db52489559f7.png)
![Screenshot 2023-02-08 at 13 36 18](https://user-images.githubusercontent.com/17083603/217545177-0a369f36-a82b-477c-8172-ea29d7ddad41.png)

**Comment by chrisraynerr** [comment]
So here, I want to add RESIDS to ResSNP$genotypes and for it to be stored in order, and in the same bk file

**Comment by privefl** [comment]
Normally you have a method `$add_columns()` to grow an FBM.

If you want to do this in parallel, this can be a bit tricky as you have to wait for the previous iterations to finish.
In such a case, if I know the size of the result in advance, I would just create the full FBM beforehand, and then fills the corresponding columns in each iteration.

Does that answer your question?

**Comment by chrisraynerr** [comment]
Ah, ok thank you. Sorry for the confusion. Screenshot of solution below in case useful for others.

![Screenshot 2023-02-08 at 14 59 15](https://user-images.githubusercontent.com/17083603/217566485-a5d7eec0-34d9-4675-b2ab-27ba6d30b625.png)

**Comment by privefl** [comment]
There is probably room for optimization, but this is good that you got this to work.
