### ISSUE TITLE
Fixed and random effect

### ISSUE THREAD

**Issue by dongleihu** [privefl/bigstatsr#165]
Recently I started to use bigstatsr to run lasso regression.  I would like to use age and sex as fixed effect and methylation as random effect in the model.  Is there a way to do this in bigstatsr?  Thank you!

**Comment by privefl** [comment]
Have you looked at the tutorial?
You can add covariates, and you can choose whether to penalize them or not.
Is this what you're looking for?

**Comment by privefl** [comment]
Any update on this?

**Comment by dongleihu** [comment]
Not really. Haven't tried it yet. Thanks for asking.

**Comment by wangnanwei** [comment]
I am not sure if I am right. PRS method is  different from linear mixed model method. No random effects are in the PRS methods

**Comment by privefl** [comment]
Any update on this?

**Comment by dongleihu** [comment]
Thank you Florian.  We have decided to take a different direction for this issue.  I think this issue can be closed now.
