### ISSUE TITLE
How to get p-value out of gwas<-big_univLinReg(...) object?

### ISSUE THREAD

**Issue by garyzhubc** [privefl/bigstatsr#168]
How to get p-values out of gwas<-big_univLinReg(...) object?

**Comment by privefl** [comment]
Please have a look at the documentation of the function, especially its example code.

**Comment by garyzhubc** [comment]
I don't think any of these works. I just want original p-values.
```
> predict(gwas,log.p =FALSE)
Error: Argument 'log.p' not used.
> stats::pnorm(gwas,log.p =FALSE)
Error in stats::pnorm(gwas, log.p = FALSE) : 
  Non-numeric argument to mathematical function
```

**Comment by privefl** [comment]
What is `class(gwas)`?
Do you have the package {bigstatsr} loaded?

**Comment by garyzhubc** [comment]
> class(gwas)
[1] "mhtest"     "data.frame"

**Comment by garyzhubc** [comment]
Also.. how to get effect sizes / beta values out of this?

**Comment by privefl** [comment]
Does `predict()` work now?

The effects sizes are stored in `$estim`.

**Comment by garyzhubc** [comment]
Work but doesn’t have the option to not logSent from my iPhoneOn Dec 11, 2023, at 11:42 PM, Florian Privé ***@***.***> wrote:﻿
Does predict() work now?
The effects sizes are stored in $estim.

**Comment by privefl** [comment]
The parameter is called `log10`, not `log.p` (cf. the examples).

**Comment by garyzhubc** [comment]
I see. Is it possible to plot adjusted p-values like using p.adjust with the plotting function?

**Comment by privefl** [comment]
No, I guess this won't be straightforward, you'll have to make the plot yourseft.
Have a look at the code of `bigstatsr:::plot.mhtest` for inspiration for the plot.
