### ISSUE TITLE
How to ensure indices of response are aligned with the genotype matrix in big_univLogReg?

### ISSUE THREAD

**Issue by garyzhubc** [privefl/bigstatsr#169]
How to ensure indices of response are aligned with the genotype matrix in big_univLogReg?

**Comment by garyzhubc** [comment]
Are the indices corresponding to rows of response or the genotype matrix?

**Comment by privefl** [comment]
You need to match your individual genotypes (rows) with the corresponding phenotypes.

**Comment by garyzhubc** [comment]
So the indices are given by rows of x not rows of y? The first row of y will need to corresponds to the indeed row of x is that correct?

**Comment by privefl** [comment]
You can set `ind.train` to choose the rows of `X` you want to use.
And then `y.train` needs to correspond to these indices as well.

**Comment by garyzhubc** [comment]
So I can use index 10 that corresponds to the first row of y and the 10-th row of X, is that right? Sent from my iPhoneOn Dec 11, 2023, at 11:48 PM, Florian Privé ***@***.***> wrote:﻿
You can set ind.train to choose the rows of X you want to use.
And then y.train needs to correspond to these indices as well.

**Comment by privefl** [comment]
Seems right.
