### ISSUE TITLE
Specify the location of the backing file resulting from `big_cor`

### ISSUE THREAD

**Issue by fmorgante** [privefl/bigstatsr#170]
Hi Florian, would it be possible to add an option to specify the location of the backing file resulting from `big_cor`?

**Comment by privefl** [comment]
I guess you want something similar to https://github.com/privefl/bigstatsr/issues/73?

**Comment by fmorgante** [comment]
Yes, something like

> backingfile Path to the file storing the Big Matrix on disk. An extension ".bk" will be automatically added. Default stores in the temporary directory.

as you have in `FBM`.

If I were to use the workaround you suggested in the other issue, would I be able to specify the backing file name? Or only the directory?

**Comment by privefl** [comment]
That would be only the directory.

I could definitely push something, but as this is quite easy to do, I was waiting for someone that wanted to contribute to the package with a PR.

**Comment by privefl** [comment]
Do you want to try?
Otherwise, I can probably push something for `big_cor()` tomorrow.

**Comment by fmorgante** [comment]
Unfortunately, I am swamped :(

**Comment by privefl** [comment]
This is now implemented in the latest GitHub version of the package.

**Comment by fmorgante** [comment]
Thank you Florian! Always super helpful!
