### ISSUE TITLE
The result is NA

### ISSUE THREAD

**Issue by Knight1995** [privefl/bigstatsr#172]
Thanks for the great job! I try to do some easy calculations on the FBM object, I want to get the 3774 rows' result,but the result is NA Could you please tell me what the problem is? Thanks!
![image](https://github.com/privefl/bigstatsr/assets/88174091/663ef3b7-d9de-403b-9afd-07ac8f485d94)
![image](https://github.com/privefl/bigstatsr/assets/88174091/8f57fdc4-a450-450c-81e2-2be8da41344f)
![image](https://github.com/privefl/bigstatsr/assets/88174091/f167c025-da39-477d-a3af-4e7c60ac2bc7)

**Comment by Knight1995** [comment]
Thanks for your quick reply! Actually,I have edited my code to calculate each row's result,but the result is also NA.
![image](https://github.com/privefl/bigstatsr/assets/88174091/fc51da82-78a5-45c0-a475-58fcfb43de38)
![image](https://github.com/privefl/bigstatsr/assets/88174091/3972ffc3-24f6-44be-87f8-03ba5febb16d)

**Comment by privefl** [comment]
Yes, cf. my first comment.

**Comment by Knight1995** [comment]
Sorry for bothering again.When I test single numble (ind=1), my code works.But I put the code into the big_apply,the results are NA. What is the problem? Does the R algorithm not work in big_apply? Thanks.
![image](https://github.com/privefl/bigstatsr/assets/88174091/3755802c-b809-46f7-93c5-2cf66da3046c)
![image](https://github.com/privefl/bigstatsr/assets/88174091/c6594932-310f-4d38-ada5-25d6619949df)

**Comment by privefl** [comment]
No, your code doesn't work when using `ind <- 1`. 
It is just that `X.sub` is of length 1 and gets automatically recycled to match the size of `K1[, 2]`.

**Comment by Knight1995** [comment]
'ind' means the row number, mean(Y[-ind, ]) means that the matrix in this row will be removed, and the mean of  new matrix will be calculated.
'Summary(Y)' shows as following.
![image](https://github.com/privefl/bigstatsr/assets/88174091/077e2972-82ae-4645-b99b-6fc2d843a55b)

**Comment by privefl** [comment]
-I didn't get that `Y` was also an FBM. Then `summary(Y[])`.

- You understand that `ind` is usually a vector of multiple indices, not just one, right?
- And you want the full `mean()` of the matrix? Not something like the `rowMeans()`?

**Comment by Knight1995** [comment]
Yes, I probably understand what you mean. I test the simple example above to konw how to rewrite the a.FUN in big_apply step by step.My original R code is below. Because the matrix is too big and it runs too slowly, I want to reliaze this function by using big_apply.cluster_info and dist are the original matrix , their rownames and number of rowa are the same.

K3<-future_map_dfr(seq(ncol(cluster_info)),function(Y){
    K2<-map_dfr(seq(nrow(cluster_info)),function(index){
      x <-cluster_info[,Y]
      dist2 <- as.data.frame(cbind(x,dist))[-index,]
      
      K1<-map_dfr(unique(x),function(i){
        d<-mean(dist2[which(dist2$x==i),index+1])  
        #d<-sum(dist2[ which(dist2$x==i),index+1])/length( which(dist2$x==i))
        
        data.frame(Value=d,clu=i) 
      })
      
      si <- (min(K1[K1$clu!=x[index],]$Value)-K1[K1$clu==x[index],]$Value)/max(min(K1[K1$clu!=x[index],]$Value),K1[K1$clu==x[index],]$Value)
      if(is.na(si)){
        data.frame(cluster=x[index],sil_width=0) 
      }else{
        data.frame(cluster=x[index],sil_width=si) 
      }
      
    })
    data.frame(Resolution=colnames(cluster_info)[Y],silhouette_score=mean(K2$sil_width))
  })

**Comment by privefl** [comment]
I don't get what you're trying to achieve here; sorry I cannot help.
