### ISSUE TITLE
Issues with locking of the backing file

### ISSUE THREAD

**Issue by dramanica** [privefl/bigstatsr#178]
Once an FBM has been instantiated, the locking of the backing file differs among Window and Linux (and its behavior is not ideal in either).
In Linux, I can delete the backing file whilst the object still exits:
```
mat <- matrix(1:4, 2)
X <- bigstatsr::as_FBM(mat)
backfile <- X$backingfile
file.remove(backfile)
```
This will obviously give an error if I try to access `X[]`

On Windows, the file is locked, but it remains so even after deleting `X`. I need to restart the session to break the lock.

The desired behavior would be a lock on the file whilst `X` is in existence, but the lock should be released when the object is deleted.

**Comment by privefl** [comment]
On Windows, you just need to call the garbage collector with `gc()`, between `rm` and `file.remove`. 

A function `big_remove()` could probably be implemented to perform these 3 actions.

**Comment by privefl** [comment]
I don't do anything special on my side IIRC.

**Comment by privefl** [comment]
So, just leave it be?

**Comment by dramanica** [comment]
I haven't got a good solution, so I guess yes. Happy to close this.
