### ISSUE TITLE
Implementation of `dimnames` for FBM matrices

### ISSUE THREAD

**Issue by dramanica** [privefl/bigstatsr#179]
There is no `dimnames` or `dimnames<-` method for FBM. A simple implementation:
``` r
#' @export
dimnames.FBM <- function(x){
  attr(x,"dim_names")
}

#' @export
"dimnames<-.FBM" <- function(x, value){
  if (any(!is.list(value),length(value)!=2)){
    stop("value for dimnames should be a list of two elements: a vector of row names and a vector of column names")
  }
  dimnames_dim <- unlist(lapply(value, length))
  if (any(dimnames_dim[1]!=dim(x)[1], dimnames_dim[2]!=dim(x)[2])){
    stop("row and column names should be the same length as their respective dimensions in the FBM")
  }
  attr(x,"dim_names")<-lapply(value, as.character)
  return(x)
}
```
provides us with the functionality (with `rownames` and `colnames` coming for free):
``` r
mat <- matrix(1:4, 2)
X <- bigstatsr::as_FBM(mat)
dimnames(X)
#> NULL
dimnames(X) <- list(c("a","b"),c("c","d"))
dimnames(X)
#> [[1]]
#> [1] "a" "b"
#> 
#> [[2]]
#> [1] "c" "d"

rownames(X)
#> [1] "a" "b"
colnames(X)
#> [1] "c" "d"
```
Note that we use `dim_names` as the attribute because `dimnames` is reserved for use with arrays.
Would you be happy if I make a pull request to add this? (if so, are you happy with `dim_names` or do you prefer something different?)

**Comment by privefl** [comment]
I am not sure I want to support dimnames for FBMs.
It would mean having to support them in some way in every function of the package, which sounds cumbersome.
Also, I'm afraid it could be somewhat detrimental to performance.

**Comment by dramanica** [comment]
It's your package, I won't fight it. I can just implement a different method for my own purposes.
