### ISSUE TITLE
control MAF filtering?

### ISSUE THREAD

**Issue by annilk** [privefl/bigstatsr#183]
Hi, when running a GWAS with `big_spLinReg` I get a message saying that some number of "variables with low/no variation have been removed". I guess this means that some variants have been filtered based on some MAF threshold? Is it possible to control which threshold is applied?

Anni

**Comment by privefl** [comment]
You must compute the MAFs (e.g. with `snp_MAF()`), and then provide those that pass some threshold with `ind.col = `.

**Comment by annilk** [comment]
Ok, thanks! I will use that. 

How the variables are filtered when user does not provide any indices for `ind.col`? Is there some default threshold for MAF?

**Comment by privefl** [comment]
There is no MAF threshold since this function is not specific to genetic data; it can be used for any matrices.

IIRC, the function checks for standard deviations lower than 1e-6 and remove those. 
This would correspond to a very small MAF threshold. Basically it checks that it is different from 0.
