### ISSUE TITLE
FBM Object Mathematical Operation

### ISSUE THREAD

**Issue by Minta821** [privefl/bigstatsr#190]
Hi,
Do we have any option to perform some mathematical operations on only few columns of FBM object, for example G is a FBM object with genetic data, I just want to reverse the value of the first column as G[,1]=2-G[,1].
It throws an error that 
In replaceMat(x$address_rw, i, j, value) :
  At least one value changed (1.78 -> 1)
  while converting from R type 'double' to C type 'unsigned char (raw)'

**Comment by privefl** [comment]
I guess you're using an `FBM.code256` with `CODE_DOSAGE` for storing dosage genotype data.

In this case, underlying values that are stored are 0, 1, 2, 3, ..., 255, and are decoded as CODE_DOSAGE[1], CODE_DOSAGE[2], ..., CODE_DOSAGE[256] when you read the matrix.

Then, when you want to replace values, you need to use the underlying values. In this case, you can use: 
```r
library(bigsnpr)
G <- FBM.code256(256, 1, code = CODE_DOSAGE, init = 0:255)
(g0 <- G[, 1])

G[, 1] <- 207 - round(g0 * 100)  # this is the formula you need to use to convert to the underlying value
G[, 1]

G[, 1] <- ifelse(is.na(g0), 3, 207 - round(g0 * 100))  # in case you also have missing values (you shouldn't)
G[, 1]
```

**Comment by Minta821** [comment]
Thank you, it is working now.
