### ISSUE TITLE
Ideas for storing/accessing large distance matrices

### ISSUE THREAD

**Issue by talegari** [privefl/bigstatsr#22]
Dear Florian Price,

Thanks for the great package!
I am attempting to write large dist objects to disk in parts and then read subsets of the distance matrix. Does `bigstatsr` support writing/reading symmetric matrices? Are there any packages/tools which already do it?

Regards,
Srikanth KS

**Comment by talegari** [comment]
Among the options available to store large distance matrices to disk, `bigstatsr` seems to be the best way to maintain it as compared to `bigmemory`, `lvec` and `ff` even if I need to store the everything twice. I believe this is not a concern as space is not a constraint. `bigstatsr` offers transparent implementations of SVD, lasso which will be helpful for me in implementing MDS on FBMs.

I would request two things:

1. A version of CRAN (https://github.com/privefl/bigstatsr/issues/19) as this would be a dependency.
2. A `big_write` function to write distances matrices to disk.

Please let me know your thoughts.

**Comment by privefl** [comment]
- For CRAN, for now a warning due to package {BH} is blocking me. I've opened an issue on the boost repo several days ago.
- For `big_write`, you want to write to a CSV format? You need this format for another soft?
  This should be easy enough with `fread` and `big_apply`. I can do this on Monday.

**Comment by talegari** [comment]
Thanks for the quick turn around!

1. Hope the BH issue resolves and CRAN release happens!
2. `big_write` to CSV is sufficient for me.

**Comment by privefl** [comment]
Please try `big_write` by installing the latest version.

**Comment by talegari** [comment]
Thanks for `big_write` and congrats on the CRAN release!
