### ISSUE TITLE
Support for float (single precision)

### ISSUE THREAD

**Issue by talegari** [privefl/bigstatsr#37]
> Is it possible to store FBM as float?

This might bring down the file size of double FBM by 2. (User may be warned about precision-loss when converted to R numeric/matrix during creation of FBM)

**Comment by talegari** [comment]
I am writing a [package](https://github.com/talegari/bigdist) to work with large distance matrices. which relies on the FBM class of bigstatsr (we discussed [here](https://github.com/privefl/bigstatsr/issues/22)). Allowing float might cut down the time on almost every operation (as long as the loss in precision is ok).

**Comment by privefl** [comment]
Ok.
I'm not sure if I will have time to work on this before the end of September. 
Do you need this quickly?

**Comment by talegari** [comment]
No urgency. Thanks for considering this.

**Comment by privefl** [comment]
Do you need a `NA` for floats?
Otherwise it would store `NA`/`NA_integer` as `-2147483648` and `NA_real` as `NaN`.

**Comment by privefl** [comment]
You can try `devtools::install_github("privefl/bigstatsr@add-float")`.

**Comment by privefl** [comment]
I've merged it in the master branch.

**Comment by privefl** [comment]
All of what you tested require some conversions between R types and C types.
As there is no 'float' type in R, I have to do some checking and conversion, which takes a bit of time.

What you can gain is when you use the `FBM` in a C++ algorithm (possibly directly using type 'float').
For example:
```
> microbenchmark::microbenchmark(
+   big_colstats(fbm_double),
+   big_colstats(fbm_float)
+ )
Unit: milliseconds
                     expr      min       lq     mean   median       uq       max neval
 big_colstats(fbm_double) 88.54033 90.73741 92.59478 92.34327 93.89756 105.86146   100
  big_colstats(fbm_float) 83.30722 85.00178 86.91936 86.40332 88.10420  99.51878   100
```

I would expect the gain to be larger for larger files and if the algorithm directly uses type 'float' (here `big_colstats()` uses variables of type 'double').

**Comment by privefl** [comment]
All of what you tested require some conversions between R types and C types.
As there is no 'float' type in R, I have to do some checking and conversion, which takes a bit of time.

What you can gain is when you use the `FBM` in a C++ algorithm (possibly directly using type 'float').
For example:
```
> microbenchmark::microbenchmark(
+   big_colstats(fbm_double),
+   big_colstats(fbm_float)
+ )
Unit: milliseconds
                     expr      min       lq     mean   median       uq       max neval
 big_colstats(fbm_double) 88.54033 90.73741 92.59478 92.34327 93.89756 105.86146   100
  big_colstats(fbm_float) 83.30722 85.00178 86.91936 86.40332 88.10420  99.51878   100
```

I would expect the gain to be larger for larger files and if the algorithm directly uses type 'float' (here `big_colstats()` uses variables of type 'double').

**Comment by talegari** [comment]
Hope you are aware of Drew's [float](https://github.com/wrathematics/float) package, but not mature yet, IMHO.

**Comment by privefl** [comment]
I was NOT aware of this package, thanks.

```
> a <- matrix(runif(1e9), 1e5)
> a[1] <- NA
> system.time(float::as.float(a))
utilisateur     système      écoulé 
      3.912       0.752       4.661 
> system.time(bigstatsr::without_downcast_warning(bigstatsr::as_FBM(a, type = "float")))
utilisateur     système      écoulé 
      3.324       1.476       4.797 
```

Seems like the timings are the same.
I'm not sure how relevant it would be to return a 'float' matrix in R.
People using type 'float' usually have a really particular application, coded in C++.

I would keep returning a 'double' matrix in R unless you provide me with a use-case where using type 'float' in R would really help.

**Comment by talegari** [comment]
As of now, the CRAN version (0.6.2) does not seem to have the float option. Do you have a timeline for CRAN release? 
PS: My package bigdist will have a dependency on bigstatsr with FBM's type defaulting to float.

**Comment by privefl** [comment]
I need my package {rmio} to go to CRAN first, then to move from {BH} to {rmio}, and then submit {bigstatsr} again.
So I'd say 2-4 weeks. Is that okay for you?

**Comment by talegari** [comment]
Thats great! Looking forward for the release on CRAN.

**Comment by privefl** [comment]
It's on its way to CRAN.
Hopefully, there won't be any problem with additional tests they run.
