### ISSUE TITLE
big_apply and big_parallelize can't find function

### ISSUE THREAD

**Issue by markabney** [privefl/bigstatsr#43]
Functions big_apply and big_parallelize can't find functions that I have defined. For instance,

```
my.sum <- function(M) {
    colSums(M)
}
mat.fb <- big_attachExtdata()
big_parallelize(mat.fb, p.FUN = function(X, ind) my.sum(X[ , ind]), ncores=2)
```

results in the error message `Error in { : task 1 failed - "could not find function "my.sum""`. This can be worked around by defining `my.sum` in the anonymous function for `p.FUN` but since the functions I want to do this for may be rather more complicated and used in other settings, it seems this should be unnecessary.

**Comment by cegbuna** [comment]
Hi, thanks for the package. Is it possible to export a list of packages in the `p.FUN` argument as well? I get an error when it can't find a function contained in a package I've used in my function.

**Comment by privefl** [comment]
I've not made this available.
You can either explicitly use `<pkg::fun()>` or `library(<pkg>)` inside `p.FUN`.
