### ISSUE TITLE
Low CPU, high RAM usage with big_parallelize

### ISSUE THREAD

**Issue by markabney** [privefl/bigstatsr#44]
I have an FBM with 33k rows and 200k columns. The entries are actually chi square values with different degrees of freedom for different rows. I am converting them to standard normal values by using big_parallelize.
My machine:
macOS 10.13.6
128GB RAM
nb_cores() -> 12

Using the code below, big_parallelize forks several (12) processes which all stay at at CPU usage of 0.1% to 0.2%. Each process initially gets allocated ~4GB RAM. Over the course of an hour or two RAM usage climbs, particularly for kernel_task, eventually resulting in the processes RAM being mostly compressed memory and all RAM on the machine is used. I'm forced to kill the R process at this point.

```
inter.fbm <- FBM(n.path.snps, n.host.snps, backingfile="../Data/interaction_matrix_new", create_bk=FALSE)
chi2z.par <- function(X, ind, df, Out.mat) {
    chi2Z <- function(chi, df) {
        qnorm(pchisq(chi, df=df))
    }
    chi2z.col <- function(M, df) {
        apply(M, 2, chi2Z, df=df)
    }
    Out.mat[ , ind] <- chi2z.col(X[ , ind], df=df)
    NULL
}

destfile <- "../Data/z_mat"
res.mat <- FBM(nrow(inter.fbm), ncol(inter.fbm), backingfile=destfile)
big_parallelize(inter.fbm, p.FUN=chi2z.par, ncores=nb_cores(), df=row.info$df, Out.mat=res.mat)
```

**Comment by markabney** [comment]
Note that taking only 10k columns from the FBM and using big_parallelize over that goes quickly (~20sec). The immediate workaround, then, is to do my own chunking and pass each chuck to big_parallelize in sequence. This leads to the following code which completes in only a few minutes.

```
chi2z.par <- function(X, ind, df, Out.mat, cols=seq_len(ncol(X))) {
    chi2Z <- function(chi, df) {
        qnorm(pchisq(chi, df=df))
    }
    chi2z.col <- function(M, df) {
        apply(M, 2, chi2Z, df=df)
    }
    Out.mat[ , cols[ind]] <- chi2z.col(X[ , cols[ind]], df=df)
    NULL
}

col.block <- 10000
last.beg <- floor(ncol(inter.fbm) / col.block) * col.block + 1
for (beg in seq(1, last.beg, by=col.block)) {
    end <- beg + col.block - 1
    end <- min(end, ncol(inter.fbm))
    cols <- beg:end
    tm <- system.time(
        empty <- big_parallelize(inter.fbm, p.FUN=chi2z.par, ind=seq_along(cols), ncores=nb_cores(),
                                 df=row.info$df, Out.mat=res.mat, cols=cols)
    )
    cat(tm, "\n")
}
```

**Comment by privefl** [comment]
Hum, this is weird. 

Could you try to reproduce this issue while generating e.g. an FBM of say 30K x 20K using some `rchisq()`?
If you could use `set.seed(1)` also, would be good.
I would really need to see some data if I want to understand what's going on.

Because I don't see anything suspicious with your code. Just one thing maybe, I don't really understand what's `row.info$df` and how you use it (if it is subsetted or not). I expected that each column of your FBM corresponded to a different `df`?

**Comment by privefl** [comment]
OK, in fact, I think I know what the problem is.

`big_parallelize()` cuts your data in `ncores` parts for parallelization.

In order to not use to much RAM, you should use `big_apply()`.
In fact, `big_apply()` uses `big_parallelize()` to enable parallelization but also, inside all `ncores` parts, accesses only chunks so that not too much RAM is used.

Basically, try using `big_apply()` instead (with `a.FUN` instead of `p.FUN`).

**Comment by markabney** [comment]
Using `big_apply` instead of `big_parallelize` in the code in my first message does solve the problem of excessive memory use. Unfortunately, the CPU usage is only partly solved. Of the 12 R processes launched by `big_apply`, they will mostly have 0.1%-0.2% CPU usage. Every handful of seconds or so, one or a few of the processes will shoot up to ~100% CPU for a few seconds before dropping back down to 0.1%. The net result is that it is still taking a very long time to run, though it does seem to make (slow) progress.

Regarding your question about `row.info$df`. The data frame `row.info` includes information for each row of the FBM. The component `$df` is a vector of length equal to the number of rows of the FBM with each vector element the degrees of freedom for that row.

**Comment by privefl** [comment]
For me, it means that the system is taking more time doing other things than doing computations (e.g. reading from disk or allocating some memory).
Are you sure this is a problem of parallelism, or do you get the same behaviour when using one core only?

BTW, I think you could avoid LOTS of memory allocation by implementing this very simply in Rcpp. Which could make this a lot faster.

**Comment by privefl** [comment]
Any update on this?

**Comment by markabney** [comment]
I ended up using the code in my second message, with big_parallelize. The difference from big_apply is in what parts of the file get sent to the different cores. I think the big_apply chunking is less efficient in terms of how it reads the data off the hard drive and sends it to the cores, resulting in lower CPU usage and a longer time to complete. Part of the issue with performance might have to do with how the OS is caching the file in RAM as it reads it from the disk, but I haven't delved into the issue more.

**Comment by privefl** [comment]
If you could help me generate some data that reproduce your problem, it would be very useful.

**Comment by markabney** [comment]
There's nothing special about the data itself, just that it's a large matrix. You could do the following.
```
nr <- 3e4
nc <- 2e5
set.seed(1)
chi2.fbm[] <- rchisq(nr * nc, 1)
```
The chi2.fbm is what I use in my code (with real rather than simulated values).

**Comment by privefl** [comment]
The code I tried:

```
library(bigstatsr)

# nr <- 3e4; nc <- 2e5
# chi2.fbm <- FBM(nr, nc, backingfile = "tmp-data/test")$save()
# 
# big_apply(chi2.fbm, a.FUN = function(X, ind) {
#   X[, ind] <- rchisq(nrow(X) * length(ind), 1)
#   NULL
# }, a.combine = 'c', ncores = nb_cores())

chi2.fbm <- big_attach("tmp-data/test.rds")
hist(chi2.fbm[, 1])
nr <- nrow(chi2.fbm)
nc <- ncol(chi2.fbm)

res.fbm <- FBM(nr, nc, backingfile = "tmp-data/test2")

# Funciton that will be used
DF <- rep(1, nr)
hist(qnorm(pchisq(chi2.fbm[, 1], df = DF)))
chi2z.par <-  function(X, ind, df, Out.mat) {
  Out.mat[, ind] <- qnorm(pchisq(X[, ind], df = df))
  NULL
}
```

With `big_apply()`:
```
# Fill with big_apply
system.time(
  big_apply(chi2.fbm, a.FUN = chi2z.par, ncores = nb_cores(), 
            df = DF, Out.mat = res.fbm)
) # 21 min  //  36 MB/s
```

With your solution:
```
system.time({
  col.block <- 10000
  last.beg <- ncol(res.fbm)
  for (beg in seq(1, last.beg, by=col.block)) {
    end <- beg + col.block - 1
    end <- min(end, ncol(res.fbm))
    cols <- beg:end
    tm <- system.time(
      empty <- big_parallelize(chi2.fbm, p.FUN = chi2z.par,
                               ind = cols, ncores = nb_cores(),
                               df = DF, Out.mat = res.fbm)
    )
    cat(tm[3], "\n")
  }
}) # 18 min
```

This is basically the same thing. Your solution may be faster because it had some values in cache as I used it second.
