### ISSUE TITLE
The bigstatsr/bigsnpr example datasets do not download from Plink

### ISSUE THREAD

**Issue by dtdibaba** [privefl/bigstatsr#47]
When I run the preprocessing R codes, it ends with: "Error: Failed to open data/POPRES_allchr_QC.bed.log Try changing the --out parameter." It might be Plink is not allowing data access. I could not access all the datasets used in the examples.

**Comment by privefl** [comment]
You need to have access access to those data. 
Do you have other datasets that you could use?

**Comment by dtdibaba** [comment]
A dataset I have is a different format that I will in the end convert to plink format and try with these packages. A simulated data will help me for sure.  I appreciate the help!

**Comment by privefl** [comment]
I've added some real public data that you can play with.
https://github.com/privefl/bigsnpr/blob/master/data-raw/public-data.zip

**Comment by dtdibaba** [comment]
Thank you, the I appreciate that!
Daniel 
-------- Original message --------From: Florian Privé <notifications@github.com> Date: 1/23/19  4:59 AM  (GMT-05:00) To: privefl/bigstatsr <bigstatsr@noreply.github.com> Cc: dtdibaba <daniel.dibaba@gmail.com>, Author <author@noreply.github.com> Subject: Re: [privefl/bigstatsr] The bigstatsr/bigsnpr example datasets do not download from Plink (#47) 
I've added some real public data that you can play with.

https://github.com/privefl/bigsnpr/blob/master/data-raw/public-data.zip

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/privefl/bigstatsr","title":"privefl/bigstatsr","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/privefl/bigstatsr"}},"updates":{"snippets":[{"icon":"PERSON","message":"@privefl in #47: I've added some real public data that you can play with.\r\nhttps://github.com/privefl/bigsnpr/blob/master/data-raw/public-data.zip"}],"action":{"name":"View Issue","url":"https://github.com/privefl/bigstatsr/issues/47#issuecomment-456740941"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/privefl/bigstatsr/issues/47#issuecomment-456740941",
"url": "https://github.com/privefl/bigstatsr/issues/47#issuecomment-456740941",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
