### ISSUE TITLE
Error in the p.combine of  big_parellelize

### ISSUE THREAD

**Issue by waldnerf** [privefl/bigstatsr#48]
I've been trying out the big_parallelize function on a FBM and my outputs were combined in a very strange way. The function defined in big_parallelize outputs of vector of the same column size as the input matrix. I would like the output to be combined using rbind so that my output matrix has the same size as the input matrix. Strangely enough, big_parallelize treats  each individual row as a vector and combines them using c(). rbind combines only the output of multiple cpus and if their size differ (which happens when nrow/ncpus is not a whole number) some outputs are removed.
Any chance you can get that fixed (I love your package otherwise)

**Comment by privefl** [comment]
**I would need some [reproducible example](https://stackoverflow.com/q/5963269/6103040) in order for me to help you.**

By default, `big_parallelize()` is returning a list of `ncores`, that corresponds to each block computation on a different core.

```
library(bigstatsr)
X <- big_attachExtdata()

### Computation on all the matrix
true <- big_colstats(X)$sum

big_colstats_sub <- function(X, ind) {
  big_colstats(X, ind.col = ind)$sum
}

test <- big_parallelize(X, p.FUN = big_colstats_sub, ncores = 2)
# length(test) is 2
```

You can merge the results (for example, here by concatenating):
```
test2 <- big_parallelize(X, p.FUN = big_colstats_sub, ncores = 2,
                         p.combine = 'c')
all.equal(test2, true)
```

If you want to fill another matrix of the same size, you should use an FBM:
```
X2 <- FBM(nrow(X), ncol(X))
big_parallelize(X, function(X, ind, X2) {
  X2[, ind] <- X[, ind] + 1
  NULL
}, X2 = X2)
```
Here, you return `NULL` because you don't want to return anything. This would return a list of 4 `NULL` because I have 4 physical cores on this computer.
Note that, in this particular example, you would use `big_apply()` instead in order to access all matrix in memory at once.

**Comment by waldnerf** [comment]
Thanks for your quick reply, your last suggestion is exactly what I was after!

**Comment by privefl** [comment]
Ok, but I didn't understand your problem. 
If you have enough memory, you can do something like this: 
```
library(bigstatsr)
X <- big_attachExtdata()
X2 <- big_parallelize(X, function(X, ind) {
  X[, ind] + 1
}, p.combine = "cbind")
all.equal(X2, X[] + 1)
```

**Comment by waldnerf** [comment]
I wanted to perform a row-wise operation on a FBM, and I guess I had the functionalities of big_apply and big_parallelize mixed up and I thought ind was actually and index, not a vector of indices. 

Another question though, since I installed "bigstatsr" I cannot complie cpp code using SourceCpp anymore. I have the following error message: 

 Error 1 occurred building shared library.

In file included from /home/wal716/R/x86_64-pc-linux-gnu-library/3.4/BH/include/boost/noncopyable.hpp(15),
                 from /home/wal716/R/x86_64-pc-linux-gnu-library/3.4/bigmemory/include/bigmemory/BigMatrix.h(11),
                 from euc_dist.cpp(14):
/home/wal716/R/x86_64-pc-linux-gnu-library/3.4/BH/include/boost/core/noncopyable.hpp(42): error: defaulted default constructor cannot be constexpr because the corresponding implicitly declared default constructor would not be constexpr
        BOOST_CONSTEXPR noncopyable() = default;
                        ^
```
In file included from euc_dist.cpp(14):
/home/wal716/R/x86_64-pc-linux-gnu-library/3.4/bigmemory/include/bigmemory/BigMatrix.h(148): warning #858: type qualifier on return type is meaningless
      const bool read_only() const
      ^

In file included from euc_dist.cpp(14):
/home/wal716/R/x86_64-pc-linux-gnu-library/3.4/bigmemory/include/bigmemory/BigMatrix.h(160): warning #858: type qualifier on return type is meaningless
      const index_type allocation_size() const {return _allocationSize;}
      ^


compilation aborted for euc_dist.cpp (code 2)
make: *** [euc_dist.o] Error 2
icpc -std=gnu++11 -I/apps/R/3.4.0/lib64/R/include -DNDEBUG   -I"/apps/R/3.4.0/lib64/R/library/Rcpp/include" -I"/apps/R/3.4.0/lib64/R/library/RcppArmadillo/include" -I"/home/wal716/R/x86_64-pc-linux-gnu-library/3.4/BH/include" -I"/home/wal716/R/x86_64-pc-linux-gnu-library/3.4/bigmemory/include" -I"/home/wal716/R/x86_64-pc-linux-gnu-library/3.4/bigstatsr/include" -I"/OSM/CBR/AF_DIGI_RS/work/projects/opt_sampling/Jaredfiles" -I/usr/local/include   -fpic  -O3 -fopenmp -xHOST -fp-model precise -c euc_dist.cpp -o euc_dist.o
/apps/R/3.4.0/lib64/R/etc/Makeconf:168: recipe for target 'euc_dist.o' failed
Error in sourceCpp(file.path(root_dir, "Jaredfiles/euc_dist.cpp")) :
  Error 1 occurred building shared library.
```

Any thoughts on how to solve this?
