### ISSUE TITLE
Check for variables with no variation

### ISSUE THREAD

**Issue by privefl** [privefl/bigstatsr#52]
Do it in scaling functions?

This is a problem when using e.g. `big_randomSVD()` because it would either stop with error `TridiagEigen: eigen decomposition failed` or run for an infinite time.

Reprex:
```
library(bigstatsr)
X <- FBM(20, 20, init = rnorm(400))
svd <- big_randomSVD(X, big_scale())
X[, 1] <- 0
svd2 <- big_randomSVD(X, big_scale())
```

**Comment by dramanica** [comment]
@privefl I just got bitten by this bug, so started looking at how to fix it. Before I do anything, I thought I would check that you are happy with what i have in mind.

I see that you suggested checking in the scaling function. But the problem I see is that, if the user provides a custom function, there is no protection against zero variance. Wouldn't it be safer to make a check just after any instance of `fun.scaling` being called that the return `ms$scale` does not contain any zeroes? I guess it does not help in cases where there is no scaling, but that would require an expensive inspection of the full dataset, which doesn't really make sense.

Or did you have something else in mind?

**Comment by privefl** [comment]
I think there is no issue when no scaling is applied.
E.g. `svd3 <- big_randomSVD(X, big_scale(scale = FALSE))`

**Comment by dramanica** [comment]
If I had thought a bit more about it, I should have realised that... Anyway, I guess it still leaves us with user-created scaling functions. Are you happy for a check of `ms$scale` after using `fun.scaling`?

**Comment by privefl** [comment]
Yes, I think it should be fine. At least make sure we do not divide by 0.
