### ISSUE TITLE
FBM-by-FBM multiplication

### ISSUE THREAD

**Issue by aslez** [privefl/bigstatsr#63]
Am I right that there is no direct way of getting x %\*% y when both x and y are FBMs?  To put it another way, what is the best way of multiplying two FBMs?  Apologies if I have missed something obvious in the documentation, but from what I can %\*% only works when you have an FBM and a vector/matrix.  Any help would be much appreciated.

**Comment by privefl** [comment]
Currently available are (cross-)products between a 'double' FBM and a numeric matrix.

It is not possible to do so for two FBMs.
It would be really easy to add this for two 'double' FBMs with the result as a numeric matrix. Yet, would it make sense to do so?

Currently, one possible way to implement this would be to use `big_apply()` to implement the block separation and multiplication yourself. You can look at the code of `big_prodMat` to get some ideas.

**Comment by aslez** [comment]
In my case, the matrices in question are currently formatted as double, though one could be formatted as an integer instead.  

When you ask does it make sense, do you mean does make substantive sense in the context of my problem or does it make sense from a computational perspective?

Thanks for the suggestion about `big_prodMat`.  I had been starting to work this up using `big_apply`; it would be nice to have an example to work off of.

**Comment by privefl** [comment]
I fear that if I'm making things too easy for people, they just will use them them wrongly. 
This is mainly why I made this sticker "CAUTION: this machine has no brain, use your own".
Big data is not an easy problem.

If you need help implementing this FBM product, I would gladly help you.
Sorry for my negative answer.

**Comment by aslez** [comment]
My particular problem can, in theory, be addressed using big_prodMat, with the second matrix passed as a regular binary matrix, as opposed to an FBM.  When I do this, I get the following error: task 1 failed - "task 1 failed - "vector memory exhausted (limit reached?).  

I could easily write a version of big_prodMat that would iterate along the rows of a second FBM matrix, but I’m not sure that would resolve the memory issue since the second FBM matrix would be handled more or less the same as a standard matrix, no?  

Really all I am trying to do is calculate the weighted crossproduct AWA’, where W is a diagonal matrix with weights along the diagonal.  I calculated AW using big_apply with A and the diagonal elements of W (i.e. the weights vector).  The task now is to do AW %*% t(A).

**Comment by privefl** [comment]
What is the size of `A`?

**Comment by aslez** [comment]
It has over a million rows, but only 100 or so columns.

**Comment by privefl** [comment]
Ok, but `AW %*% t(A)` would end up being a 1M x 1M matrix, right?

**Comment by aslez** [comment]
Right.

**Comment by privefl** [comment]
You can't get the eigendecomposition of a 1M x 1M matrix, right?
Would be easier to compose `A` or `t(A) %*% A`, by using a proper scaling to account for `W`.

**Comment by privefl** [comment]
It is generally not a good idea to compute such a matrix.
What do you need to do with it afterwards?

**Comment by aslez** [comment]
I'm not sure what you mean when you say it is not a good idea to compute such a matrix.  Do you mean it is computationally problematic to try and work with something of that size?  In the end, I need to take the eigenvalues/vectors of `D %*% AW %*% t(A)`, where `D` refers to another diagonal weights matrix.

**Comment by privefl** [comment]
You need the complete eigendecomposition or just the first values (e.g. 10)?

**Comment by aslez** [comment]
I just need the second eigenvector.

**Comment by privefl** [comment]
Then you might want to use `RSpectra::eigs_sym()` with `k = 2` and `A` being a function of `x` that computes `D %*% (A %*% (W %*% crossprod(A, x)))`.

**Comment by privefl** [comment]
Were you able to what you wanted?
