### ISSUE TITLE
colnames

### ISSUE THREAD

**Issue by nbenn** [privefl/bigstatsr#64]
Any reason why `FBM`s don't do colnames? If no, interested in a PR?

**Comment by privefl** [comment]
Hum, I never use colnames / rownames for matrices.
Plus, it is sometimes very inefficient to use very large vectors of different strings.

What would be your use of names for `FBM`s?

**Comment by nbenn** [comment]
> What would be your use of names for `FBM`s?

I don't know what to say here apart from the obvious: column names are a feature of base R matrices and users of your package might expect an `FBM` to implement the base R matrix API where ever this makes sense. My personal reason for wanting column names is indexing matrix columns by name.

> it is sometimes very inefficient to use very large vectors of different strings

In line with your "This machine has no brain, use your own" mantra, one could expect it to be up to the user to decide when row-/column names make sense and when they don't. In my case for example (50M rows and 300 cols), I don't think column names would cause efficiency problems.

I'm closing this issue, as I feel like you're not interested in column names and I can work around this by using attributes. Thanks anyways.
