### ISSUE TITLE
Remove columns

### ISSUE THREAD

**Issue by nbenn** [privefl/bigstatsr#65]
Is it possible to add a method `remove_columns()` to `FBM`s that does the inverse of `add_columns()`, i.e. removes n columns from the end of of an `FBM`? Or are there technical reasons why this is not implemented?

**Comment by privefl** [comment]
For now, it seems that you can partially do it:
```
> library(bigstatsr)

> X <- FBM(10, 10)

> file.size(X$backingfile)
[1] 800

> X$add_columns(2)

> file.size(X$backingfile)
[1] 960

> dim(X[])
[1] 10 12

> X$add_columns(-5)

> file.size(X$backingfile)
[1] 960

> dim(X[])
[1] 10  7
Warning message:
Inconsistency of backingfile size after adding columns. 
```

But there is an issue of the file not being smaller.
It may be just a matter of changing a few lines of code here to solve this.

**Comment by privefl** [comment]
One question is "do we really want the file to be smaller or just access only part of the data?".
Because removing columns in the file would make these data lost forever.

What is your opinion on this?
Again, I want to here more from other users (including you) and the use cases they need {bigstatsr} for.

**Comment by nbenn** [comment]
One reason for requesting this was finding a way to delete rows of a `FBM` with a maximal storage overhead of sizeof(col). I thought this might be achieved using two `FBM`s, and doing col-by-col subsetting and copying, growing the one file and shrinking the other.

I have a [prototype](https://github.com/nbenn/bigstatsr/compare/cpp17-resize), using cpp17 filesystem features:

``` r
library(bigstatsr)

X <- FBM(10, 10)

file.size(X$backingfile)
#> [1] 800

X$add_columns(2)

file.size(X$backingfile)
#> [1] 960

dim(X)
#> [1] 10 12

X$rm_columns(5)

file.size(X$backingfile)
#> [1] 560

dim(X)
#> [1] 10  7
```

<sup>Created on 2019-05-10 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

If you don't like the idea of cpp17, a combination of [SetEndOfFile](https://docs.microsoft.com/en-us/windows/desktop/api/fileapi/nf-fileapi-setendoffile) for Windows and [truncate](http://pubs.opengroup.org/onlinepubs/9699919799/functions/truncate.html) for POSIX compliant systems should do the job as well.

**Comment by privefl** [comment]
Sorry, but I don't get
> One reason for requesting this was finding a way to delete rows of a FBM with a maximal storage overhead of sizeof(col). I thought this might be achieved using two FBMs, and doing col-by-col subsetting and copying, growing the one file and shrinking the other.

I'm not sure it is a good idea to use cpp17 with R at the moment.

**Comment by nbenn** [comment]
I guess you're right about cpp17. For POSIX systems I [implemented the same](https://github.com/privefl/bigstatsr/compare/master...nbenn:posix-resize) using [truncate](http://pubs.opengroup.org/onlinepubs/9699919799/functions/truncate.html). This has to be handled separately for Windows. I guess Windows support is important to you, right?

Regrading removing rows with sizeof(col) storage overhead, maybe code can communicate better what I mean:

```r
delete_rows <- function(x, rows,
  new_file = tempfile(tmpdir = dirname(x$backingfile))) {

  stopifnot(is.numeric(rows) || is.logical(rows))

  if (is.numeric(rows)) {
    rows <- unique(-rows)
  } else {
    rows <- which(!rows)
  }

  res <- bigstatsr::FBM(length(rows), ncol(x), type = bigstatsr::typeof(x),
                        backingfile = new_file)

  for (j in rev(seq_len(ncol(x)))) {
    res[, j] <- x[rows, j]
    # removing the last col throws an error
    if (j != 1) x$rm_columns(1L)
  }

  res
}
```

**Comment by privefl** [comment]
If you want to copy a subset of the matrix, you can use `big_copy()`.

Maybe I should allow to use negative indices in this function.

**Comment by privefl** [comment]
Any update on this?
