### ISSUE TITLE
Serialization using qs

### ISSUE THREAD

**Issue by nbenn** [privefl/bigstatsr#66]
Have you had a look at the [qs](https://github.com/traversc/qs) package for `FBM` serialization? This might offer more performant serialization.

**Comment by privefl** [comment]
I didn't know about this package, thanks.

Reading the README, it seems that the main difference with RDS format is that it is faster. 
Generally, the `.rds` file is very small (as it just store the class object, not the data, which is stored separately in the `.bk` file). Thus, it should take only 1-2 seconds to save/read to/from the rds file associated with an FBM.

Are you experiencing some slowness here?

**Comment by nbenn** [comment]
I'm sorry, I was under the impression that `save()` serializes the entire data associated with a `FBM`. That's why I thought `qs` could be interesting. I'm currently not using `save()` and no, I'm not experiencing any performance issues with the current implementation. I'll close the issue.
