### ISSUE TITLE
Crash when using big_cprodMat() with very large FBMs

### ISSUE THREAD

**Issue by shuvani511** [privefl/bigstatsr#74]
I have been trying to use big_cprodMat(X1,X2) for a while now. X1 is a FBM of the dimensions 177304 * 23, and X2 is a FBM of the dimensions 23*177304. The output should have the dimensions 177304 * 177304. 

However, R keeps crashing before it can do this. I was wondering if it first computes the output as a matrix-class object and if there was anyway to make the function big_cprodMat() output a FBM instead. I know that big_apply can be used as an alternative but I find it strange that I cannot use the cross-product function directly.

**Comment by privefl** [comment]
First, given the dimensions of your two matrices, I'm confused why you need a **cross-**product and not simple a matrix product?

Second, `big_cprodMat()` and `big_prodMat()` output some standard R matrix my default. I could extend them to be output an FBM instead (related to https://github.com/privefl/bigstatsr/issues/73).

**Comment by privefl** [comment]
I close this due to inactivity.
