### ISSUE TITLE
Error in big_splinreg when using covariates with low variability

### ISSUE THREAD

**Issue by mj-thompson** [privefl/bigstatsr#75]
I've encountered a few times the error "Please use covariables with some variation." I notice that my covariable, sex for example, might be something like this:

c(1,1,1,1,1,1,1,2,2).

And while there is some variation, I believe the problem occurs during the CMSA/model-fitting and cross validation procedure. Namely, if it subsets the above vector in the training steps so it now looks something like this:

c(1,1,1,1,1,1,1) and all individuals have the same sex.

Is it possible so that this is changed to only be a warning, and to remove the covariable from this step of the CMSA/cross-validation procedure? I have attempted to add some checking/condition statements to my code to prevent the error, but I'm having a hard time getting around it.

The problem arises when I wish to fit many different models, because this error may occur after a few hours of computation and stop the script's execution (rather than warn and go around the problem). I have not encountered this issue with glmnet, but maybe that is because the explanatory matrix in glmnet is usually a combination of the random variables X, as well as the covariates C and looks something like this:

Y ~ [XC]

Is there any way to change this error to warning, and to fit the model without the offending covariate? If not, would you recommend adding the covariable to the the FBM or regressing the low-variable covariates out of the dependent variable prior to fitting?

Thank you for your help and great work.

**Comment by privefl** [comment]
I see, thanks for reporting.

I'm a bit surprised you end up having subsets with no variation.
How large is your data? How much is it unbalanced?

Two ways to get around this:
- You can provide `ind.sets` to be sure that there is no set where there is no variation.
- You can add the covariates in the FBM using `$add_columns()`, where the columns with no variation are silently removed.

Honestly, it was just easier for me to code it that way.
And I won't have time to make the necessary changes before 15 days at least.

**Comment by mj-thompson** [comment]
Thanks for your help. 

The data ranged from 40-300 individuals in each model. Adding the covariates to the FBM worked out perfectly.
