### ISSUE TITLE
Sample weights argument for big_sp(Lin/Log)Reg 

### ISSUE THREAD

**Issue by brieuclehmann** [privefl/bigstatsr#76]
Would it be possible to add a sample weights option for the penalised regression functions (like in glmnet)?

**Comment by brieuclehmann** [comment]
My use case is for a (sparse) genotype matrix where you have different uncertainty for each sample (i.e. individual) which you could account for using sample weights. 

In theory, adding sample weights just amounts to optimising a slightly different loss function, i.e. a weighted version of the log likelihood plus the same penalty term. What that means in terms of implementation... I'm not familiar enough with the algorithm to say for sure but my naive guess would be to add a sample weight multiplier whenever the log likelihood appears.

**Comment by privefl** [comment]
Hum, if you find a nice publication that explains how to implement this easily, I might doing it.
Otherwise, I won't have time to search for this by myself for now.

Also note that if you sparse data, you might just use {glmnet} that handles sparse matrices and sample weights if I remember correctly.

**Comment by brieuclehmann** [comment]
Thanks for the suggestion! I did look at glmnet but my data is too big to read into memory so I don't think that will work unfortunately.

The glmnet paper https://www.jstatsoft.org/article/view/v033i01 does have some details about how to implement sample weights - see especially Section 2.4. I don't know how relevant it is for this, though.

Alternatively, could you point me to the publication(s) explaining the implementation of big_spLogReg? I'd be very happy to derive the maths for the sample weights.

**Comment by privefl** [comment]
In the latest versions, you get the 3 relevant publications in the help `?big_spLogReg`.

**Comment by brieuclehmann** [comment]
If I understand correctly, the implementation needs adjustments to:

1) the pathwise coordinate descent algorithm
2) the sequential strong rules
3) the computational simplifications applied in biglasso

I think 1) is described in Section 2.4 of https://www.jstatsoft.org/article/view/v033i01 . I've derived 2) and 3) and will type it up in the next day or two.

Am I missing anything else?

**Comment by brieuclehmann** [comment]
If I'm not mistaken, I think that would be covered by 3). Are you referring to the scaling (and centering) of X?

**Comment by privefl** [comment]
Yes

**Comment by brieuclehmann** [comment]
OK, this I've derived too. I could try to implement it myself but I might need a bit of help getting my head around the code structure...

**Comment by privefl** [comment]
R code: https://github.com/privefl/bigstatsr/blob/master/R/biglasso.R
- `null_pred()`: computes the null prediction y_bar, including intercept and covariates with pf=0.
- `summaries()`: computes scaling and residuals for all CV folds.
- `COPY_biglasso_part()`: fit model in one fold
- `COPY_biglasso_main()`: do `null_pred()` + `summaries()` + the CV calling the `COPY_biglasso_part()`.
- `big_spLinReg()` and `big_spLogReg()`: dispatch if linear or logistic
- `get_beta()`: different ways to merge the resulting models, not really used.

C++ code fitting the regularization path: https://github.com/privefl/bigstatsr/tree/master/inst/include/bigstatsr/biglasso

**Comment by brieuclehmann** [comment]
I've (finally) had a go at implementing this for the linear lasso and the existing tests seem to run without error... There aren't too many changes and I don't think changing the logistic lasso will be too difficult either.

By the way, I've not contributed to other packages before - how should I share my code?

**Comment by privefl** [comment]
The best is to fork this repo and modify your copy of the code.
Then you can submit the changes for approval in a pull request.

**Comment by privefl** [comment]
I would need some strong incentive for it (i.e. show an example where this is very useful), and to show that this is does not affect runtimes.

Closing for now.
