### ISSUE TITLE
inverses with FBM

### ISSUE THREAD

**Issue by abuegho** [privefl/bigstatsr#80]
Thanks for the AWESOME package, by the way.
I checked out the majority of functions built into the package. I have a pretty good idea on why there isn't a 'big_solve' function, but is there a way to find an inverse to an FBM using `big_apply()`?

Thanks Florian,

**Comment by privefl** [comment]
Thanks.

What is the size of the FBM you would like to invert?
What would be the use you think of `big_apply()`?

**Comment by abuegho** [comment]
FBM is 500k×500k
I was just thinking of `big_apply()` as just an example.. I had in mind perhaps using the definition of the inverse to calculate it, but I'm not sure how computationally efficient it would be. I'm trying to see if there is some clever linear algebra property that I completely missed  which would be faster.
Thanks,

**Comment by privefl** [comment]
Inversion is typically O(N^3), meaning that it would be impossible for N=500K.
It can already be quite slow for N=50K.

Is this matrix resulting for the cross-product of some other matrix?

**Comment by abuegho** [comment]
Oops, sorry, it's actually 20k×20k! (I've looking at this for way too long) 
This matrix is the result of a `crossprod(x)`; x is a 500k×20k.. I'm basically trying to construct the projection matrix of this monster.

**Comment by privefl** [comment]
You mean the full projection matrix? Or just need a few components?

N=20K is not too much I think, so you could access it directly as a standard R matrix (i.e. use `eigen(X[], symmetric = TRUE)`).
Otherwise, I'm sure that we could use an RcppArmadillo operation directly on the `FBM`, yet I'm not sure it would be much faster (maybe twice as fast).

**Comment by abuegho** [comment]
Gotcha. Before I learned about bigstatsr, I was trying to operate with Rcpp, as it was faster. But it's definitely good to know about it works with FBM as well. I'll try it and get back to you.
But to answer your question, the end goal is to extract the diagonal elements of the projection matrix (data are heteroscedastic, and I'm trying to make necessary adjustments)

**Comment by privefl** [comment]
Any update on this?

**Comment by abuegho** [comment]
Yes thank you! it took a while, but it worked!
Thanks for your support!
