### ISSUE TITLE
Error in big_spLinReg

### ISSUE THREAD

**Issue by msesia** [privefl/bigstatsr#84]
The following code 
```
## Load packages
library(bigsnpr)
set.seed(1)
# simulating some data
N <- 230
M <- 730
X <- FBM(N, M, init = rnorm(N * M, sd = 5))
y <- rowSums(X[, 1:10]) + rnorm(N)
covar <- matrix(rnorm(N * 3), N)

ind.train <- sort(sample(nrow(X), 150))
ind.test <- setdiff(rows_along(X), ind.train)

# fitting model for multiple lambdas and alphas
test <- big_spLinReg(X, y[ind.train], ind.train = ind.train, covar.train = covar[ind.train, ],
                     alphas = c(1, 0.5, 0.1, 0.01), ncores=10)
```
gives this error:
`Error in { : task 1 failed - "could not find function "summaries""
`
Package versions: bigsnpr_1.0.1   bigstatsr_1.0.0

**Comment by privefl** [comment]
Thanks for reporting.

I tried with {bigstatsr} version `1.0.0` and I don't get any error.
Can you please tell more about your session info?

**Comment by privefl** [comment]
I managed to reproduce a similar problem: https://stackoverflow.com/q/59197177/6103040.
Are you using Windows?

**Comment by msesia** [comment]
No, I'm using Linux. Since I couldn't fix it, I eventually decided to delete my conda environment and reinstall your package in a clean environment. Somehow that worked.
