### ISSUE TITLE
Slower big_spLinReg/big_spLogReg

### ISSUE THREAD

**Issue by msesia** [privefl/bigstatsr#88]
I have observed that big_spLinReg_ and big_spLogReg are both much slower than they used to be in an earlier version (bigsnpr 0.9.1, bigstatsr 0.8.4), at least with large data (n=400k, p=1.2M).
Setting dfmax=10k and using 10 cores, the same job that used to take 12 hours now takes approximately 2 days (and sometimes fails due to an error reading in the SOCK connection).

**Comment by privefl** [comment]
Could this be a memory problem? 
Can you check if the cores are running at 100%?

There are two phases in the algorithms:
- a first pass of the whole dataset to compute some statistics. It is possible that this does not run at 100% if your file is not cached in memory, but this should be fast anyway as it does not need a lot of computations, say 1 hour for the size you're mentioning (just a few minutes if the file is cached).
- a second phase that fit the models, that should use much less variables (so could have everything cached in memory) thanks to the strong rules. This should be running at 100% for all cores.

**Comment by msesia** [comment]
I'm not sure how to check the cores, since this is running on a computing cluster. I also don't really know how this package uses memory. How much memory should I request for a job with the size described above? I'm requesting 20GB right now, and it's not using more, but I don't know whether this is optimal.

**Comment by privefl** [comment]
The data you're using is 450 GB.
You should ask for at least 100GB. 
If you expect the architecture to be polygenic (i.e. large `dfmax`, you should ask for more).

I use to run only interactive sessions. And have the system command `top` always running.

**Comment by msesia** [comment]
OK, this is good to know. I will try. Perhaps it would be good to have some instructions and guidelines about this provided with the package (I apologize if it's already there and I missed it).
I'm still confused about one thing though. Did the memory management change since last February? I'm pretty sure it was much faster back then, all other things equal.

**Comment by privefl** [comment]
I will add this information to this vignette in the coming days: https://privefl.github.io/bigstatsr/articles/penalized-regressions.html.

In February, I changed the way I was mapping the files from 'boost' to 'mio' because there were some problems with boost on CRAN.
But, based on the benckmarks I made, it shouldn't change anything.

Do you know exactly the version of {bigstatsr} you were using?

**Comment by msesia** [comment]
I was using the following versions: (bigsnpr 0.9.1, bigstatsr 0.8.4).
I don't know exactly which commit they corresponded to. Is there a stable version of bigstatsr and bigsnpr? I'm afraid nothing is working for me anymore.

**Comment by privefl** [comment]
All versions are kind of stable as I test every commit on the 3 main OS and they pass..

How do you install the packages and dependencies on your server?

**Comment by msesia** [comment]
OK, I just cleaned my system. Now I'm using R v3.5.1 (compiled by the system administrators) and Then I installed the latest version of your packages using devtools in a local user library (other packages were installed from CRAN ). Even though #90 seems solved, the main problem persists: big_spLinReg/big_spLogReg are much slower than they used to.

Before the update, I used to be able to run big_spLinReg on (n=350k, p=1.2M) in less than 12 hours, setting dfmax=10k, using 10 cores, and 20GB. Now applying the same settings (but more memory: 50GB) with a much smaller problem (n=50k, p=600k, less polygenic) takes much longer.

I suppose it is possible there may be something wrong on my server side. However, it's suspicious that the problems only occurred after I updated my R library (including bigstats). Have your tried to run these functions on problems of this size? Do you know approximately how long it should take?
Assuming there nothing meaningful changed on my server, any ideas why it should be slower now?

**Comment by privefl** [comment]
Yes, I did run it on the UK Biobank; see the published paper:  https://doi.org/10.1534/genetics.119.302019.
In the published version of this paper, there is also a whole section on memory and time requirements (what I explained before).

I would suggest to install the previous versions you were using before and compare computation time all things equal.
I will try to do the same on my side.

**Comment by msesia** [comment]
Hi Florian,

Based on the output of "top", it would seem that the cores are not working correctly. This is an example of what it looks like.

   PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                     
 56935 msesia    20   0   28.2g 435700 338740 S  10.9  0.2   0:06.31 R                                           
 56956 msesia    20   0   28.2g 447432 350472 S   1.3  0.2   0:06.49 R                                                                              
 56892 msesia    20   0   28.2g 415212 318244 S   0.7  0.2   0:06.16 R                                                                                
 56913 msesia    20   0   28.2g 411304 314348 S   0.3  0.2   0:05.89 R                                           
 57022 msesia    20   0   28.2g 419944 322988 S   0.3  0.2   0:06.00 R                                           
 57045 msesia    20   0   28.2g 430792 333836 S   0.3  0.2   0:06.42 R                                                                                                    
 56818 msesia    20   0   28.5g 369112  11236 S   0.0  0.1   0:12.11 R                                           
 56870 msesia    20   0   28.2g   1.4g   1.3g S   0.0  0.5   0:11.86 R                                           
 56979 msesia    20   0   28.2g 429560 332596 S   0.0  0.2   0:06.22 R                                           
 57001 msesia    20   0   28.2g 441192 344232 S   0.0  0.2   0:06.35 R                                           
 57067 msesia    20   0   28.2g 409728 312772 S   0.0  0.2   0:05.69 R

**Comment by privefl** [comment]
I believe you are still in the first step computing the statistics.
The CPU is not good because it has to load the data from disk.
You can see that the memory is not full.

In the second step, if you have some issues, I expect that the CPU is like this but that the memory sums up to 100%, meaning that you are swapping.

**Comment by msesia** [comment]
Are the statistics computed using only one thread? Why spawn 10 processes then?
This is what the output of top for the same command using the older version of your packages looks like: 

 64803 msesia    20   0   28.2g 853044 763128 S  23.2  0.3   0:20.93 R                                           
 64847 msesia    20   0   28.2g   2.3g   2.2g S  22.8  0.9   0:27.63 R                                           
 64760 msesia    20   0   28.2g 804472 714556 R  21.5  0.3   0:20.40 R                                           
 64781 msesia    20   0   28.2g 853280 763368 S  21.2  0.3   0:20.85 R                                           
 64738 msesia    20   0   28.2g   2.2g   2.1g S  20.2  0.9   0:26.77 R                                           
 64890 msesia    20   0   28.2g 829572 739648 S  20.2  0.3   0:20.61 R                                           
 64868 msesia    20   0   28.2g 763680 673760 S  19.9  0.3   0:19.62 R                                           
 64911 msesia    20   0   28.2g 797768 707844 S  17.5  0.3   0:20.15 R                                                                              
 64684 msesia    20   0   28.5g 383692  12844 S   0.0  0.1   0:10.73 R                                           
 64717 msesia    20   0   28.3g   2.9g   2.8g S   0.0  1.1   0:28.92 R                                           
 64826 msesia    20   0   28.3g   2.9g   2.8g S   0.0  1.1   0:18.13 R                                           

For some reason two processes are not running, but at least the other 8 are doing something.

**Comment by privefl** [comment]
Yes, the statistics are computed in parallel, split in 10 blocks, and each do its block.

This does not look very different to me. 
Are your file on some faststorage (meaning that accesses to disk are kind of fast)?

**Comment by msesia** [comment]
Yes, access to the disk should be very fast. OK, maybe I made some progress.
I deleted the memory mapped file and generated it again. Now CPU usage is always at 100% and the job is very fast. What am I missing? Could the memory mapped file have been somehow corrupted? Are memory mapped files generated with different versions of bigsnpr incompatible?
I will try to delete the file again and run everything with the latest version.

**Comment by privefl** [comment]
No the versions should not change the files.

The access is faster because the file is cached (because you just wrote it).

**Comment by msesia** [comment]
Every seems to be working fine also with the latest version of the packages, as long as I create a new FBM file every time I run the script. This is good enough for me.
However, I'm curious: what's the recommended practice?
Suppose I have to run multiple instances of the problem in parallel (e.g., studies of different phenotypes). I used to have them share on FBM file (and I'm pretty sure it worked fine), but that doesn't really work (it has all the problems discussed earlier). What do you recommend?

**Comment by privefl** [comment]
Having only one file should be fine..

The only time it matters is if you are using a small subset of individuals. Using a whole file with all individuals and accessing only a subset is the same as accessing them all because data is stored variant-wise.

**Comment by privefl** [comment]
Just to let you know:
I reproduced the same timings for the breast cancer and height UKBB results from the paper.
