### ISSUE TITLE
Error: Two levels of parallelism are used. See `?assert_cores`.

### ISSUE THREAD

**Issue by msesia** [privefl/bigstatsr#90]
Latest versions of big_spLinReg and big_spLogReg do not work. I suspect there may be a problem with bigparallelr. I'm trying to use them with 10 cores (I have the 10 cores) and this is the error message I receive:
**Error: Two levels of parallelism are used. See `?assert_cores`.**

Which functioning version of "bigstatsr" and "bigsnpr" would you recommend using? I was satisfied with the functionalities implemented in bigsnpr 0.9.1, bigstatsr 0.8.4).

**Comment by privefl** [comment]
Yes, it is a new check I just introduced.
It is for when you have enabled parallel matrix computations by default, it can slow everything because of too much parallelism used.

Have you looked at `?assert_cores` and https://github.com/privefl/bigstatsr/issues/78?

**Comment by msesia** [comment]
I see, I think I got around this by running "export OPENBLAS_NUM_THREADS=1" before calling R.

**Comment by privefl** [comment]
There is an explanation (in the doc of `assert_cores()`) how to do this within R and once and for all.

**Comment by msesia** [comment]
Ok, that works too. Thanks.
