### ISSUE TITLE
Multi-thread reading an FBM as a standard R matrix

### ISSUE THREAD

**Issue by dipterix** [privefl/bigstatsr#92]
Is there any support for multi-thread reading large matrices in either R or cpp level?

**Comment by privefl** [comment]
You would have to be more precise on what you're thinking about when you say "reading".

**Comment by dipterix** [comment]
Let's say I have 100 GB FBM data that I want to load all of them from file system into RAM (I define this as reading). The data is file saved on SSD drive (or any other hardware that can be sped up using multi-threaded reading). What's the fastest way to load it using your framework.

**Comment by privefl** [comment]
Basically, you want to access the FBM as a standard R matrix?
And you have enough RAM?

**Comment by dipterix** [comment]
That's just an example. Let's say we have enough RAM.

**Comment by privefl** [comment]
I would do something like
```r
# Reprex
library(bigstatsr)
X <- big_attachExtdata()

# Simple way (sequential)
mat <- X[]

# Access as standard matrix in parallel (need RAM twice the size of `X`) 
mat <- big_parallelize(X, function(X, ind) {
  X[, ind]
}, p.combine = "cbind", ncores = nb_cores())
```

**Comment by dipterix** [comment]
How about c++ side? Can I create multiple accessors to achieve this goal?

**Comment by privefl** [comment]
I don't follow.
`X[, ind]` is just calling some C++ code to access the data.

**Comment by dipterix** [comment]
I see. So if I have one `BMAcc` instance, can I expect a speed boost from the following code?

```cpp

// [[Rcpp::export]]
NumericVector get_elements(Environment fbm) {
  
  XPtr<FBM> xpMat = fbm["address"];
  BMAcc<double> macc(xpMat);
  
  int n = macc.nrow();
  int m = macc.ncol();
  
  NumericVector res(m * n);
  
  // Parallel this part
  
  <<some_parallel_along j>> {
    <<some_parallel_along i>> {
      res[j * n + i] = macc(i, j);
    }
  }
  
  return res;
}
```

or should I use multiple `BMAcc` instances for each parallel "block"?

```cpp
NumericVector get_elements(Environment fbm) {
  
  XPtr<FBM> xpMat = fbm["address"];
  
  // For each columns, create one accessor
  <<parallel for j in 0 to m-1>> {
    // create multiple accessors
    BMAcc<double> macc(xpMat);
    for (int i = 0; i < n; i++) {
      res[j * n + i] = macc(i, j);
    }
  }
  
  return res;
}
```

**Comment by privefl** [comment]
I think you can parallelize only over the columns if you have enough of them.

I am not sure if you can really write to some `NumericVector` in parallel.
I think you would need to use {RcppParallel}. I tried at some point for {bigsnpr} (see https://github.com/privefl/bigsnpr/compare/newparallel) but it did not really work better.

This is a lot of work; are you sure you really need to speed-up accessing data that much?
The 2 options I proposed should be fine.
And normally, you don't just access data, but perform some computations on these blocks as well.

**Comment by privefl** [comment]
Any update on this?
