### ISSUE TITLE
Allowing for dimnames in FBMs

### ISSUE THREAD

**Issue by alperyilmaz** [privefl/bigstatsr#97]
I have an existing matrix saved as rds file and I wanted to process it via bigstatsr package. But, I guess I couldn't grasp the concept of FBM and I desperately need help. Although I like and understand [disk.frame](https://github.com/xiaodaigh/disk.frame), I'm having great difficulty using `bigstatsr`.

My aim is to move a large matrix to an old computer with small RAM and I'll be doing random row selection as batches for some downstream analysis. (_since I'll be doing row selection, I'll be transposing the FBM in the sample code below_)

The matrix has 61,000 rows and 12,000 columns. The matrix is available as `bigm.rds`. My first step was to convert the matrix into FBM.

```R
bigM <- readRDS("bigM.rds")
bigM_fbm <- as_FBM(bigM, backingfile="bigM")
bigM_fbm$save()    # some functions does not save rds automatically
```
Then I noticed that the `.bk` file is 5GB and I was not able carry with usb drive due to FAT32 file size limit. Then I found out that `big_write()` generates smaller file size.

```R
big_write(bigM_fbm, "bigM_write", every_nrow = 10000, progress = interactive())
# bigM_write is around 1.7GB, carry that file to other computer
# in other computer, run the following
bigmat <- big_read("bigM_write",1:12000)
transposed <- big_transpose(bigmat, backingfile="bigM_t")
transposed$save()
```

Now I can process the file in new session as follows:
```R
bigM.t <- big_attach("bigM_t.rds")
test <- bigM.t[,1:10]   # let's get first 10 cols as example
rownames(test)          # let's get the rownames
                                   # NULL     oh no!
```
To my surprise,  colnames and rownames are lost, although original matrix had them. I know, `big_read()` and `big_write()` are for dealing with text files but due to small file size they generate I used them.
Also, I saw options for saving the matrix as chunks but I saw single `.bk` files at my each trial.

So, how can I convert an existing matrix to FBM, preferably with multiple chunks if possible, while retaining row and column names?

**Comment by privefl** [comment]
Dimnames are not very efficient to work with and therefore I chose not to support them.
It would be some significant work to allow for them. I guess if someone has some time to do it, I'll surely accept a pull request :-)

You can always store them yourself in the FBM file I think, but they won't be used seamlessly (you would have to do the matching yourself).

**Comment by privefl** [comment]
To transfer files, I think you can always zip the bk/rds files together.
It should compress them a bit (as you seem to have integers in your matrix).

**Comment by alperyilmaz** [comment]
Thanks for the help. When I zipped the backing file in went from 5GB down to 821MB.. That's more transferable..

About the chunks, if I understood correctly, no matter how big is the input file size, a single backing file is generated, right? In that case, there's no possibility of dividing the the FBM into parts/chunks on disk then..

**Comment by privefl** [comment]
A multi-backingfile FBM is not implemented yet in {bigstatsr}.
I've thought about implementing one for a long time but I've never had a use case that would balance the workload of implementing this.

I think {bigmemory} has this feature if you really need it.
